### ISSUE TITLE
es67-linux-daemon/daemon/README.md is not correct

### ISSUE THREAD

**Issue by muca78** [bondagit/aes67-linux-daemon#1]
JSON RTP source example parameter: 

> "max_samples_per_packet": 48,

while in explanation there is no value "48":

> where:
> max_sample_per_packet JSON number specifying the max number of samples contained in one RTP packet. Valid values are 12, 16, 18, 96, 192.

**Comment by bondagit** [comment]
Thanks, this is fixed by 4a5f2f8
