### ISSUE TITLE
AES67 Daemon sources are not handled properly by Audinate Dante Controller

### ISSUE THREAD

**Issue by bondagit** [bondagit/aes67-linux-daemon#10]
Dante Controller is currently able to succefully show the AES67 daemon Sources announced via SAP. Despite this when trying to connect a daemon channel to a receiver via the Dante Controller Routing dialog the green connection icon doesn't show up and a prohibition icon is shown instead. 

See image below:

![dante_controller_routing](https://user-images.githubusercontent.com/56439183/85580238-d7ea3e80-b63b-11ea-90b3-4311098a1fdb.png)

In the image note the prohibition icons when connecting the daemon channels 1-8 to a Yamaha MRX7 device channels 1-8.
The image also shows how instead a successful connection of a Dante AVIO AI2 device (channels 1-2) to the same MRX7 device (channels 9-10) shows up in the Routing configuration dialog.

In addition to this the Dante Controller is not updating properly the daemon announced sources in the Routing dialog in case these get updated or deleted.

Despite the problems reported above the RTP audio flow is working as expected.

**Comment by bondagit** [comment]
The problem is related to a wrong handling of the Session ID / Session version fields (o= ...) in the SDP files associated to the AES67 Daemon sources.
I am currently working of a fix.

**Comment by bondagit** [comment]
After commit cee8823 Dante Controller can properly handle the daemon sources advertised via SAP.
Prohibition icons are now shown in the proper box in case a no playback is active on the daemon source.
Green icons are shown in case a playback is active on the daemon source, see picture below:
![dante_controller_routing1](https://user-images.githubusercontent.com/56439183/85917325-78697a00-b859-11ea-8cc8-727e61c4cfbe.png)

**Comment by keygee** [comment]
Hi Andrea,
I can confirm that last commit works perfect with a Yamaha MTX5-D DSP Audio Processor
Thank you very much for your work
Guido

**Comment by bondagit** [comment]
Hi Guido, thanks for the feedback. I close this issue. Andrea
