### ISSUE TITLE
Need advice 

### ISSUE THREAD

**Issue by drommedaris** [bondagit/aes67-linux-daemon#109]
I am working on a project connecting linux aes67 to QSC core system for some time now.  In the mean time a lot of (security?) updates have come around.  Since then I am no longer able to connect to the Core via aes67. (SDP errors) It looks like the PTP clock is not able to get to the locked state. The aes67 tests worked fine . Do have an idea how to approach this issue?

**Comment by bondagit** [comment]
SDP errors ? Can you please clarify where do you see these errors ? if they come from the daemon you should some traces associated to them.
Regarding daemon PTP clock not getting locked you have to analyse the network traffic and try to understand if the PTP master clock packets are reaching the daemon host. You can use a tool like Wireshark for such purpose.

**Comment by bondagit** [comment]
any update on this ?

**Comment by drommedaris** [comment]
Hi Andrea

My test environment is laptop with dante virtual soundcard => Q-lan to core QSC =>Linux
Dedicated network, no other devices on the network. Switch is a Dell 1108, 1Gb network
The core will be the grandmaster.
Dante (audio) works fine until the linux driver comes in:
The dante controller logs “ptp clock unlocked”. Causing dante audio errors..
When  the linux driver is stopped,  dante controller shows “PTP clock locked” again.
Interestingly the linux aes67 webpage still shows “slave” and “locked”. But this is aes67… and the core gave “initialized”.
A stream to the core gives SDP errors.
Dante controller shows the core is no longer grandmaster. The linux system took over PTP  grandmaster?(showing mac address.)

I also checked the Core network settings (Q-lan)

I did not have time to analyze what is happening on the network… (work in progress)
But  dante controller gave me important hints to look for.

linux i5 16GB 512Gb i210 network card (audio) + internal network onboard.
Tested with ubuntu 20 and 22



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by bondagit** [comment]
Please consider the linux driver is a PTP slave only and it's completely passive on the network: no PTP packets are sent by the linux driver, unless you have configured ptp4l on the same host.  
When the daemon starts it joins the multicast address 224.0.1.129 to receive the PTP packets and it leaves the the multicast address when it stops.
