### ISSUE TITLE
ALSA sinks going idle

### ISSUE THREAD

**Issue by whyronimus** [bondagit/aes67-linux-daemon#110]
**SOLVED: DANTE switches had Multicast package filtering enabled. Either it needs to be disabled or adjusted to needs.**

First of all, many thanks for your work on the AES67 linux daemon.

I'd like to describe my setup:

AES67 linux daemon is installed on a debian 11 server and running as service. The server is connected to a DANTE network which spans multiple parts of a larger building. Network is set to DHCP, relevant devices are set to AES67 compatibility mode. A possible source of trouble is the cable length, it is CAT7, but more than 50m, if not 100m.

What I  want to do is to feed the stereo sum of two mixing consoles (Yamaha DM2000 and O2R) to the server. Both do have Yamaha MY16-2 DANTE expansion cards built in. The multicasting devices are recognized in the Web GUI Browser and can be added as sink. Audio signal reception works well - first.

The problem is that one Sink (the mixing console O2R which is much further away in terms of cable length) is reported as "idle" after two minutes or similar time. Audio signal is dropped. The multicast still is visible in the Browser view of AES67 Web GUI, but it stays "idle" in the sink view and does not switch back to "receiving". From DANTE controller and the sending device config, it is clearly visible that the signal is still broadcasted. In the output of aes67-daemon I couldn't find anything helpful. Signal path between the server and the O2R device is going through two cisco switches and one D-Link switch. The device much nearer (DM2000) works flawlessly.

I tried to set all buffer sizes in AES67 linux daemon config to a larger value but with no effect. 

My question is, is there any way of diagnosis for such behaviour? 
I am not sure if the problem is related to sync or something AES67-specific. Is there any log output or test result which I can provide?

Many thanks in advance for any answer.

**Comment by bondagit** [comment]
The first thing to verify if the RTP packets are reaching the daemon hosts after two minutes. 
So use tcpdump on the debian host and capture the full RTP session to a file, for example:

`tcpdump -i eth0 udp port 5004 -w capture.pcap`

You can analyse the file with Wireshark or you can enclose it here.

**Comment by whyronimus** [comment]
Thanks a lot! I have the following results:

Within the first short time span packets originating from the O2R Dante are registered, with the multicast address shown in the config. (I didn't measure if it's exactly two minutes). After the short time span, they disappear and the sink is reported "idle".
Would this indicate a network problem? The DANTE connection works fine.

Another bad or strange news is that I noticed the nearer device also went "idle" after a much longer time span, although the packets still were there. At least, they were there when I noticed, I wasn't able to find out if there was a short interruption of network connections. Is there anything such as a buffer size or RTP-specific setting in one of the switches which could cause the problem?

For my basic understanding, the AES67 Daemon creates or "hosts" the RTP addresses which are used as multicast flow adresses as virtual network interfaces, or how is this implemented?

**Comment by bondagit** [comment]
When a sink is created the daemon joins the multicast address associated to the stream's destination address.
This happens in case the destination address is a multicast IP address. 
The daemon will leave the group on termination or in case the sink is removed.
You can check the active multicast address on the available network interfaces with:

`ip maddress show`

**Comment by bondagit** [comment]
BTW. on the linux host make sure PulseAudio is not running and possibly remove it:
See: 
https://github.com/bondagit/aes67-linux-daemon#notes

**Comment by whyronimus** [comment]
Thanks again! PulseAudio never was installed.

Both addresses which are shown in the browser as RTP adresses of the sources are among the addresses listed on the interface. 
I added the sink using the SDP which I could choose from the dropdown menu.

Could the problem be related to Multicast Package TTL? 
The Device which comes "idle" and whose packets do not reach the server after a short timespan is located 3 hops away (the D-Link and two Cisco switches). The device whose connection works fine is just 1 hop, which is the D-Link switch.

**Comment by bondagit** [comment]
You can see the remote Source TTL in the connection (c=) attribute of the sink SDP file.
For example:

`c=IN IP4 224.2.1.1/127`

After the slash you have TTL, 127 in this case.
Anyway, If the problem was related to TTL you should never receive the RTP stream.

**Comment by whyronimus** [comment]
I thought so, but you never know if a router has a "grace period" of forwarding or anything even more obscure.
(TTL is 127, thus unlikely the cause.)

So multicast address is active on the interface, but packet's are not arriving there.
Is there any switch setting I should pay attention to? Type is Cisco CBS350-48T-4G-EU.

**Comment by bondagit** [comment]
check the TTL in the IP header of the RTP packets to make sure it's set as expected. 
Check:
https://www.cisco.com/c/en/us/support/docs/ip/ip-multicast/16450-mcastguide0.html

**Comment by whyronimus** [comment]
TTL in Wireshark for the incoming packets is reported as 32 - strange, but still I'm not crossing 32 hops. 

`Internet Protocol Version 4, Src: XXX.XXX.XXX.XXX, Dst: XXX.XXX.XXX.XXX
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x88 (DSCP: AF41, ECN: Not-ECT)
    Total Length: 328
    Identification: 0x0000 (0)
    010. .... = Flags: 0x2, Don't fragment
    ...0 0000 0000 0000 = Fragment Offset: 0
    Time to Live: 32
    Protocol: UDP (17)
    Header Checksum: 0xf497 [validation disabled]
    [Header checksum status: Unverified]
    Source Address: XXX.XXX.XXX.XXX
    Destination Address: XXX.XXX.XXX.XXX
User Datagram Protocol, Src Port: 61455, Dst Port: 5004
Data (300 bytes)`

**Comment by whyronimus** [comment]
**Problem is solved.**

DANTE switches had Multicast package filtering enabled. Either it needs to be disabled or adjusted to needs.
