### ISSUE TITLE
Increasing availability - howto for sound technicians?

### ISSUE THREAD

**Issue by SM0VXI** [bondagit/aes67-linux-daemon#112]
I have from time to time tried to use this software in different productions that I'm involved in. On every occasion I had to give up and use a commercially available alternative. I have realised that for a sound technician (like me) it is a pretty steep curve to get it running unless you also happen to have skills in compiling software. 
 To increase availability for the average sound technician, is there any kind soul out there who has knowledge and time to write a step by step howto, to get the aes67-linux-daemon running?

**Comment by bondagit** [comment]
I will try to summarise here the operations required to have the daemon up and running quickly. 

1. Install on your target machine (both ARM or X86) an Ubuntu Linux distribution. The daemon should work on all Ubuntu  starting from 18.02 onward.
2. Install all the required packages by running the script [ubuntu-packages.sh](https://github.com/bondagit/aes67-linux-daemon/blob/master/ubuntu-packages.sh)
3. execute the [build.sh](https://github.com/bondagit/aes67-linux-daemon/blob/master/build.sh) script to download and build the driver, the daemon and the WebUI.
4. edit the daemon configuration file [daemon/daemon.conf](https://github.com/bondagit/aes67-linux-daemon/blob/master/daemon/daemon.conf) and change the _interface_name_ parameter to the ethernet network interface you want to use. Ex: _eth0_
5. install the driver by executing from the main folder:
```
     cd 3rdparty/ravenna-alsa-lkm/driver
     insmod ./MergingRavennaALSA.ko
```
6. start the daemon by executing from the main folder:
```
     cd daemon
     ./aes67-daemon -c daemon.conf
```
7. open a browser and load the daemon configuration WebUI at http://[your_ip]:8080
8. on the WebUI use the Browser tab to see the other ASE67 Sources advertised on the network.
9. on the WebUI use the Sinks tab to create a receiver by specifying a remote Source manually or by selecting one of the remote Source discovered (check the _Use SDP option_ to enable this).
10. on the WebUI use the Sources tab to create a daemon source 
11. on the WebUI use the PTP tab to check the status of the daemon PTP slave. Receiving or sending audio via the ALSA RAVENNA device is only possible is the PTP is locked. 
12. Playback on the RAVENNA ALSA device to send audio via a Source, for example for a stereo source use:

    `speaker-test -D plughw:RAVENNA -r 48000 -c 2 -t sine`

14. Record from the RAVENNA ALSA device to receive audio via a Sink, for example for a stereo sink use:

    `arecord -D plughw:RAVENNA -c 2 -f cd -d 30 -r 48000 -t wav sink.wav`

15. To run interoperability tests with other AES67 devices, for example with Dante devices use instruction at:
    
     [Devices and interoperability tests](https://github.com/bondagit/aes67-linux-daemon/blob/master/DEVICES.md)

Try with the instructions above and let me know if they work for you.

**Comment by bondagit** [comment]
To make things easier in the future you could ship daemon packages for different Linux distributions. 
Unfortunately the need for a Linux kernel module makes the things a bit more complex than shipping a simple application.

**Comment by markamber** [comment]
Everything worked very well for me in a virtual machine (so far) however it’s worth noting that I’m running a pretty high end setup (dual 22 core Intel Xeon, Intel X710 nics with SR-IOV, VMware ESXI)

my use case now is just sound input but just as a data point it does work. I had to set the VM as “highly latency sensitive” in the VMware setup.

**Comment by bondagit** [comment]
ok, interesting. 
If you have a Dante device please check the Latency reported. This is the important measure in this regard.

**Comment by bondagit** [comment]
can you successfully run the daemon latency test ?

**Comment by markamber** [comment]
I noticed that the tester did not work (I think this was the “main” tester and not the specific one for latency) but I also noticed it might have been trying to run a PTP clock. 

I can’t add a PTP clock to this network or add a Dante device because it is a PTP2 only LAN, on a production network. Is the latency test also going to make a ptp clock? Or was I misinterpreting the output of the other test?

**Comment by markamber** [comment]
@bondagit do you have another communication channel to avoid derailing this issue? you may be interested in my tests and we may have a use case that requires added consulting. I cannot get the latency test to work, and it seems it was indeed starting some sort of ptp master unless my eyes deceive me

(the VM is not a for sure thing at this point, but nevertheless it is extremely convenient for our application and seems to be working thus far)

**Comment by bondagit** [comment]
the guide has been integrated into the README.md
