### ISSUE TITLE
Plan for additional samplerates?

### ISSUE THREAD

**Issue by jnk19** [bondagit/aes67-linux-daemon#114]
Hi,

I have some devices that are capable to go on higher sample rates 192, 384khz. 

Can this be added on newer release?

King regards.

**Comment by bondagit** [comment]
Sample rates 192, 384 kHz should be already supported but they are not enabled in the WebUI because I have never tested them :-) 
Just try to setup a source or a sink and specify the desired sample rate at playback/capture time. 
The RAVENNA device should support the sample rates between 44100 and 384000.

**Comment by jnk19** [comment]
‎Yes I have tried with a sink but I have SAC error, probably it is working but the samplerate is wrong.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/bondagit/aes67-linux-daemon/issues/114#issuecomment-1438871314",
"url": "https://github.com/bondagit/aes67-linux-daemon/issues/114#issuecomment-1438871314",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]‎

**Comment by bondagit** [comment]
this is confirmed also my side: sample rates from 192Khz on are not working

**Comment by bondagit** [comment]
I fixed the issue in the driver and the sample rate 192Khz and 384Khz should now work properly. 
Can you please checkout the daemon branch [issue-124](https://github.com/bondagit/aes67-linux-daemon/issues/114) and retry ? 
Please consider you also need to use the new driver branch [aes67-daemon-issue11](https://github.com/bondagit/ravenna-alsa-lkm/tree/aes67-daemon-issue11) .
The build.sh script in the new daemon branch will checkout the correct driver.

**Comment by bondagit** [comment]
I used a A Mini PC N40 with Intel® Celeron® Processor N4020 , 2 Cores/2 Threads (4M Cache, up to 2.80 GHz). See [Minisforum N40 Mini PC](https://store.minisforum.com/products/minisforum-n40-mini-pc)

**Comment by siraaris** [comment]
With the above branch and running build.sh the default sample rate on the main screen only enables up to 96khz. Not sure if this is because the html is pulled and it hasn't been updated?

**Comment by bondagit** [comment]
Yes, correct this happens because the pulled WebUI doesn't containt the changes. If you have the npm installed you can build it. Check the build.sh for building it. -------- Messaggio originale --------Da: Aris Theocharides ***@***.***>Data: mer 26 apr 2023, 15:57A: bondagit/aes67-linux-daemon ***@***.***>Cc: Andrea Bondavalli ***@***.***>, Comment ***@***.***>Oggetto: Re: [bondagit/aes67-linux-daemon] Plan for additional samplerates? (Issue #114)
With the above branch and running build.sh the default sample rate on the main screen only enables up to 96khz. Not sure if this is because the html is pulled and it hasn't been updated?

**Comment by bondagit** [comment]
I have found the issue causing the problem and I have just released a new patch for the driver.
Can you please checkout the daemon branch [issue-114](https://github.com/bondagit/aes67-linux-daemon/tree/issue-114) and retry ?
Please consider you also need to use the new driver branch [aes67-daemon-issue11](https://github.com/bondagit/ravenna-alsa-lkm/tree/aes67-daemon-issue11) .
The build.sh script in the new daemon branch will checkout the correct driver.

**Comment by bondagit** [comment]
> For interest, what's the spec of the platform that you get the above test results? I have a fairly beefy setup and don't get anywhere near that level of throughput.

I have found the issue causing the problem and I have just released a new patch for the driver.
Can you please checkout the daemon branch [issue-114](https://github.com/bondagit/aes67-linux-daemon/tree/issue-114) and retry ?
Please consider you also need to use the new driver branch [aes67-daemon-issue11](https://github.com/bondagit/ravenna-alsa-lkm/tree/aes67-daemon-issue11) .
The build.sh script in the new daemon branch will checkout the correct driver.

**Comment by bondagit** [comment]
solved starting with driver v1.7
