### ISSUE TITLE
way to control volume ?

### ISSUE THREAD

**Issue by tellierflexus** [bondagit/aes67-linux-daemon#118]
Hello everyone, 
When trying to output to plughw:RAVENNA, i figure the volume is way to high and seems to be amplifying my signal. Is there a way I could control the volume out and in ?

alsamixer only show master volume which seems to have no effect

Have a good day :)

**Comment by bondagit** [comment]
volume control is not implemented in RAVENNA ALSA device, the driver never alters the original samples amplitude.

**Comment by tellierflexus** [comment]
Ok thank you :)
