### ISSUE TITLE
Testing support

### ISSUE THREAD

**Issue by markamber** [bondagit/aes67-linux-daemon#121]
In exchange for a reasonable donation would you be able to look synchronously at our deployment and see if we can get the latency test running and how far we can push it as far as number of channels of receive audio or if we need to procure more dedicated hardware?

referring to https://github.com/bondagit/aes67-linux-daemon/issues/112

**Comment by bondagit** [comment]
you can contact me directly at the email andrea.bondavalli74@gmail.com
