### ISSUE TITLE
Unnecessary multicast join() for sources

### ISSUE THREAD

**Issue by bjornwein** [bondagit/aes67-linux-daemon#124]
Hi,
I'm using IGMP snooping to reduce multicast and AES67 traffic in parts my the network where it is not wanted.
However, I stumbled across inconsistent behaviour between aes67-daemon multicast and some other sources.
It seems like aes67-daemon always joins its own sources, which makes itself a subscriber of those multicast groups from the perspective of IGMP snooping. At least in one corner case, this bypasses my IGMP snooping.

The culprit seems to be the `igmp_.join()` call in `session_manager.cpp::on_add_source`, as I get the expected behaviour when that is commented away.
If there's no explicit reason for that join() call, I think it could just be removed. It is normally only multicast _receivers_ that need to join multicast groups. Unless you for some reason want to always receive your own data.

I propose this simple change:
```c++
@@ -483,10 +483,6 @@
   for (auto cb : add_source_observers) {
     cb(source.id, source.name, get_source_sdp_(source.id, info));
   }
-  if (IN_MULTICAST(info.stream.m_ui32DestIP)) {
-    igmp_.join(config_->get_ip_addr_str(),
-               ip::address_v4(info.stream.m_ui32DestIP).to_string());
-  }
   source_names_[source.name] = source.id;
 }
 
@@ -494,10 +490,6 @@
   for (auto cb : remove_source_observers) {
     cb(info.stream.m_uiId, info.stream.m_cName, {});
   }
-  if (IN_MULTICAST(info.stream.m_ui32DestIP)) {
-    igmp_.leave(config_->get_ip_addr_str(),
-                ip::address_v4(info.stream.m_ui32DestIP).to_string());
-  }
   source_names_.erase(info.stream.m_cName);
 }
```

**Comment by nicolassturmel** [comment]
Hello,

to the best of my knowledge, joining as group as a sender is a good practice, it also allows the routers and querier to know that such address is available on the network and allows the router to be configured to block unregistered multicast.

plus, a routeur will never send à packet back to it’s origin MAC.

**Comment by bjornwein** [comment]
Thank you for taking time to respond.
I haven't heard about it being "best practice" before, and would love it if you could pass me some reference to read up on that?

Anyhow, I've been going through my test setup and figured out that there's more going on than I thought before, and I can't reproduce my previous successful results with the patch above. 
I also noticed that my simple solution breaks the multicast loopback option on the socket, which wasn't intended.

So I'm closing this and apologizing for the noise. If I come back on this I'll make sure to have details and results better fleshed out.

**Comment by doughecka** [comment]
As a side note, switches should not forward traffic received on a port back out that same port, so joining a group as the sender should not result in the sender receiving its own traffic.
