### ISSUE TITLE
Daemon Timeout

### ISSUE THREAD

**Issue by dwillisSAV** [bondagit/aes67-linux-daemon#125]
Testing a small Celeron box on Ubuntu 22.04 and am passing the system and daemon tests with no issues.  Everything looks good.  When running `systemctl start aes67-daemon`, it hangs up.  The web GUI starts, I can see devices on the network discovered - looks like it's working - then it hits a timeout error and the service stops.  I'm more than happy if I can assist in any way to locate this issue, but you'll have to instruct me like a child because I don't know what I'm doing.

Attached are the results of `journalctl -xeu aes67.daemon.service`:
[journalctl.txt](https://github.com/bondagit/aes67-linux-daemon/files/11402442/journalctl.txt)

**Comment by dwillisSAV** [comment]
To Add: I increased the timeout to 3 minutes and it still died, so I think it is more than the machine being slow.  Here are the results of `systemctl status aes67-daemon` just before the timeout occurred - if that helps at all.
[systemctlStatus.txt](https://github.com/bondagit/aes67-linux-daemon/files/11402491/systemctlStatus.txt)

**Comment by mspangen** [comment]
I was just about to submit an issue with this exact problem, until I saw this one.

I am on Ubuntu 22.04 and my system passes all tests with "OK". The service stays in the "activating" phase for a couple of minutes and then times out. I can access the web interface during those couple of minutes.

My first thought was that it times out because I don't have any AES67 devices active on my network, but it sounds like @dwillisSAV sees active devices, and his still times out.

I wonder if we are both missing something in our setup...

**Comment by bondagit** [comment]
It looks like you are using the daemon without the Systemd support enabled. Please make sure you compiled the daemon with the `-DWITH_SYSTEMD=ON` enabled.
By default this option is disabled.
Go in the` build.sh` script and change `-DWITH_SYSTEMD=OFF` to `-DWITH_SYSTEMD=ON`
Rerun build.sh and re-copy the daemon binary to the final destination .

**Comment by bondagit** [comment]
any update on this ?

**Comment by Play-AV** [comment]
Had this problem too crop up a couple weeks ago when I was doing the config on another system.  Bondagit's suggestion should fix it. I just ended up going back to my old way of launching the daemon. 

By the way these newer ultra cheap Celerons are fantastic for AoIP stuff. They're all over my place now.

**Comment by dwillisSAV** [comment]
My apologies for the delay - my test box had to move on to its real purpose in life (I was testing this before I deployed it for a customer - I usually have them for a week or two before they are delivered).  I will test this again when I receive another unit.  Tried in a VM and almost nothing worked, so I think that was a VM limitation.  So I'll just wait for another physical unit.

**Comment by Play-AV** [comment]
> My apologies for the delay - my test box had to move on to its real purpose in life (I was testing this before I deployed it for a customer - I usually have them for a week or two before they are delivered). I will test this again when I receive another unit. Tried in a VM and almost nothing worked, so I think that was a VM limitation. So I'll just wait for another physical unit.

VMs will not work unless you really know what you're doing (and even then...). I haven't even bothered to delve too far into it. You'd probably be able to make it work if you're directly passing a NIC through to the system. I've been able to pull rtp aes67 streams on VMs  (like if I wanted to say, log or record it) but you're not getting the benefits of PTP then.

**Comment by bondagit** [comment]
any update ? did you manage to install the daemon under systemd?

**Comment by jaques-sam** [comment]
Also got the error, I know it's in the readme, but a script's option would be nice ;-)

**Comment by jaques-sam** [comment]
Update: when enabling I got this error:
```
/aes67_daemon/daemon/main.cpp:35:10: fatal error: 'systemd/sd-daemon.h' file not found
#include <systemd/sd-daemon.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
It's solved by adding `libsystemd-dev` to the docker dependencies.
