### ISSUE TITLE
cannot create more than 8 sources or 8 sinks using the WebUI

### ISSUE THREAD

**Issue by bondagit** [bondagit/aes67-linux-daemon#13]
I hit a problem trying to receive the 10 channel stream that I was receiving before. 
I get the following error from the driver:

`CManager::get_live_in_jitter_buffer() failed: retrieving channel #9 buffer jitter buffer`

I can receive 8 channels or less but the sink creation fails with the following error if I try receiving 9 or 10 channels.
Same happens when creating more than 8 sources.

**Comment by jtc-dolby** [comment]
Verified Fixed
