### ISSUE TITLE
Suggestion: Display Node ID in all web GUI tabs

### ISSUE THREAD

**Issue by druidlabs** [bondagit/aes67-linux-daemon#130]
When managing multiple systems using the web GUI, it's easy to lose track of which system you're looking at.  Currently the only place where an identifier is shown is the Node ID field in the Config tab.  Would it be possible to see that value displayed somewhere, no matter which tab is active?

**Comment by Play-AV** [comment]
I style the interface a tiny bit anyways so I've just added it as a CSS change in my userstyle for each node's IP. Frankly you could just change the webUI on a per node basis but that isn't elegant. 

Not ideal but it's helped. 

#root > div > div > div > h1 {
            visibility: hidden;
    position: relative;
}
#root > div > div > div > h1:after {
    visibility: visible;
    position: absolute;
    top: 0;
    left: 0;
    content: "NODE NAME HERE";
}

Appending a node name to the "AES67 Daemon" heading somewhere gets my vote.

**Comment by bondagit** [comment]
![Screenshot 2023-05-19 at 15 44 25](https://github.com/bondagit/aes67-linux-daemon/assets/56439183/b23e6aed-b545-4b5d-9ca7-7bb74d269f09)
Is this ok for you ?

**Comment by Play-AV** [comment]
Absolutely.  :) 
Id argue you don't need the 'Version' in the header. It's not particularly useful to be to be displayed on every page. Whereas node name / ID makes a ton of sense to have easily visible wherever we are. 

Thanks <3

**Comment by bondagit** [comment]
The WebUI shows the daemon NodeId and address on all the pages
