### ISSUE TITLE
Error w/ Kernel Module "Invalid Parameters" - Issue & Fix

### ISSUE THREAD

**Issue by Play-AV** [bondagit/aes67-linux-daemon#131]
After a power outage last night, one of my first endpoints I set up (the one I use for headphones primarily) stopped functioning. Took a couple minutes to trace the issue but for some reason, when the system would try to load the kernel module, it would get an "invalid parameters" error. 

I'm not knowledgeable enough to know 'what' specifically went wrong or changed, but there is a fix if you receive this error. Clear out the driver directory of any build files, and rebuild. After that, the module can be inserted / loaded no problem.

**Comment by bondagit** [comment]
is it possible that your distro is updating the kernel automatically and the new version gets applied after a restart ? 
This would explain the need to recompile the module with the new kernel version.
Check if you have automatic updates enable.

**Comment by Play-AV** [comment]
> is it possible that your distro is updating the kernel automatically and the new version gets applied after a restart ? This would explain the need to recompile the module with the new kernel version. Check if you have automatic updates enabled.

Yeah that was absolutely it. I thought I had them disabled but checking 
/var/log/unattended-upgrades/ shows logs. 

Weird that it took 6+ months for this to happen. 
*shrugs* 


I'll probably change my startup automation to handle the possibility of this (rebuild if an error is thrown)
