### ISSUE TITLE
Driver not inserted after reboot, with systemd support? Linux Mint 21

### ISSUE THREAD

**Issue by druidlabs** [bondagit/aes67-linux-daemon#133]
I'm setting up systemd support for the driver, on a Linux Mint 21 system.  When I reboot the system the systemd task for the driver fails, because the kernel module isn't present.  If I manually insert the module using insmod and then start the systemd task, then everything starts up OK.

Is the kernel module supposed to be inserted automatically after boot?  If not, what is the appropriate way to do so? Thanks.

**Comment by bondagit** [comment]
You can usally install the module using the following commands:

```
cd 3rdparty/ravenna-alsa-lkm/driver
sudo make modules_install
```
If this doesn't work because you miss kernel certificate follow the instructions at: [No OpenSSL sign-file signing_key.pem](https://superuser.com/questions/1214116/no-openssl-sign-file-signing-key-pem-leads-to-error-while-loading-kernel-modules)

Finally use the command to load the modules:

`sudo depmod -a`

After these the module will load automatically at startup time.

**Comment by bondagit** [comment]
any updates on this ?

**Comment by druidlabs** [comment]
No luck, I'm afraid.  I did this test:

- Created a new Linux Mint 21 system, brought it up to date, installed git, and cloned the AES daemon project.
- Installed the required build packages with `ubuntu.sh`, and the Mint-specific libstdc++ package.
- Modified `build.sh` to set `SYSTEMD=ON` and built the project.
- Did the systemd installation steps using `systemd/install.sh`.
- Issued the `systemctl` command, which failed because the driver is not active. `Kernel module not loaded?`

Then I did this:
- Built the driver as you suggested. Got a couple of warnings (see below), but it looked OK. The `depmod` command did not issue any messages, and I see the MergingRavenna driver listed in the `modules.dep` file.
- Reissued `systemctl`, which still failed with module not loaded.
- Issued `insmod` for the driver and reissued `systemctl`.  This worked, and the daemon started running.

Finally, I rebooted.  
- The daemon was not started and `journalctl` showed the "not loaded" error.  
- I issued `insmod` and the daemon was able to be started.

It looks like everything is working except the driver load at boot. Suggestions?

![image](https://github.com/bondagit/aes67-linux-daemon/assets/8617969/0cfd168c-5a45-40ed-a6dd-1eb548431a3a)
