### ISSUE TITLE
Use AES67 in centos

### ISSUE THREAD

**Issue by JiangP95** [bondagit/aes67-linux-daemon#135]
” The daemon and the test have been verified starting from Ubuntu 18.04 distro onwards for ARMv7 and x86 platforms “

Can I use AES67 in the Centos system ？

**Comment by bondagit** [comment]
Yes of course. There is no dependency between the daemon and the Linux distro.

**Comment by JiangP95** [comment]
Thanks for your reply!  I have another question

Host environment: centos
Server environment: My service runs inside the Docker container, Docker container system version Centos7
My requirement: I need to obtain audio data on my server
Can I directly deploy the AES67 program in the Docker container and obtain audio data in my program

**Comment by JiangP95** [comment]
Thanks for your reply! I have another question

Host environment: centos
Server environment: My service runs inside the Docker container, Docker container system version Centos7
My requirement: I need to obtain audio data on my server
Can I directly deploy the AES67 program in the Docker container and obtain audio data in my program
