### ISSUE TITLE
PTP timestamps accesiblity 

### ISSUE THREAD

**Issue by anthonio9** [bondagit/aes67-linux-daemon#138]
Hi, 

Are PTP timestamps available somehow through the ravenna-alsa-lkm code or the daemon? I can see some fields in the TClock_PTP structure of the PTP.h file, however I'm not entirely sure of their role. Which one of them bears the information of the timestamp of the audio sample arrival? 

Thanks!

**Comment by bondagit** [comment]
the RTP packet timestamp used above is the original RTP packet timestamp subtracted by the RTP timestamp offset advertised via the SDP file (_sync-time_ attribute of the audio media).
