### ISSUE TITLE
Kernel hang when attempting a playback on the RAVENNA device using memory mapped access mode

### ISSUE THREAD

**Issue by bondagit** [bondagit/aes67-linux-daemon#14]
Starting from revision 9aaa517 initiating a playback on the RAVENNA device using memory mapped mode (SND_PCM_ACCESS_MMAP_XXX access mode) results in a kernel hang.
To reproduce the problem:
- create a Source with L24 codec at 48Khz
- wait for the PTP slave to lock
- initiate a playback with:
    `aplay -D plughw:RAVENNA -M -r 48000 -c 2 ./myfile.wav`

**Comment by jtc-dolby** [comment]
This problem was confirmed by me as playback using portaudio stopped working and according to http://portaudio.com/docs/v19-doxydocs-dev/pa__linux__asihpi_8c.html
portaudio uses memory mapped access mode. I retested after the fix and found the issue with portaudio resolved.

**Comment by bondagit** [comment]
James, thanks for the feedback. I close the issue then.
