### ISSUE TITLE
 aplay -l not showing other source or sink i added

### ISSUE THREAD

**Issue by shahid-tk** [bondagit/aes67-linux-daemon#142]
```**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC3234 Analog [ALC3234 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: RAVENNA [Merging RAVENNA], device 0: Merging RAVENNA [Merging RAVENNA]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```
idk its a problem or not i have configured .asound.conf also

**Comment by shahid-tk** [comment]
![Untitled](https://github.com/bondagit/aes67-linux-daemon/assets/67534099/594e235f-caf7-49c2-9d33-fde42868db58)

**Comment by bondagit** [comment]
The RAVENNA device you see is a 64-channel audio codec that can be used for playback and recording.
When you create Sources or Sinks you define a channel mapping with the RAVENNA codec.
How you play your Sources or record your Sinks is completely independent of the channel mapping you defined.
The RAVENNA codec supports ALSA plugins, so you can use the Dmix and Dsnoop plugins if you want several simultaneous playbacks and recordings, see https://github.com/bondagit/aes67-linux-daemon/issues/107 for some working examples.
