### ISSUE TITLE
Status in Dante Controller stays as "prohibited"

### ISSUE THREAD

**Issue by timsu100** [bondagit/aes67-linux-daemon#143]
I'm using Ubuntu 22.04 on a Intel NUC.

the self test is working. The source shows up in Dante Controller. While running `speaker-test -D plughw:RAVENNA -r 48000 -c 2 -t sine` the icon still stays red and no sound is played. Hovering over the icon shows: RTP Subscription Status: No audio data.

<img width="413" alt="image" src="https://github.com/bondagit/aes67-linux-daemon/assets/27164706/82fe34de-7e68-4e7d-b7bd-7bae63563836">
<img width="399" alt="image" src="https://github.com/bondagit/aes67-linux-daemon/assets/27164706/aa0784fe-8da3-4c1f-8559-133557bf65e6">
/
<img width="1175" alt="image" src="https://github.com/bondagit/aes67-linux-daemon/assets/27164706/27a3416b-7557-41e9-ade5-a10dafccb9cb">

<img width="278" alt="image" src="https://github.com/bondagit/aes67-linux-daemon/assets/27164706/795cd3da-400f-463e-98b5-a9c1eb6c2102">

The daemon log shows no errors, only info messages.

**Comment by bondagit** [comment]
Configuration looks correct: your PTP slave status is synced and your source is configure as L24@48Khz.
On the host where the daemon is running you should be able to sniff the outbound audio traffic on the port 5004 with:
`sudo tcpdump -i enp86s0 port 5004`
You can use _Wireshark_ to verify the network traffic on another host on your network.
Make sure enp86s0 is the network interface you want to use,.

**Comment by timsu100** [comment]
The tcpdump command shows lots of outgoing packets.

Using https://aes67.app/ on my notebook I can tune in to the stream and receive audio.

**Comment by bondagit** [comment]
Chek the latency measured on the Dante device. You can configure it for 2ms or 5ms latency.

**Comment by timsu100** [comment]
It was 1ms, i changed it to 5ms, sadly it changed nothing.

**Comment by bondagit** [comment]
Try to check if multicast mode is enabled, see:
>Yamaha MY16-2 does not seem to acccept connections from AES67 source.
>Icons stay at "prohibited" state, RTP Subscription status is "No Audio". Firmware is latest.
>Connection to DANTE AVIO seems to work (have not listened to it but green Icons do show).
>Are there any settings I can provide? TIC frame size is 48 (1 ms).
>Edit: I got it to work by assigning the RTP Address to the source. manually. This might be an important hint.
