### ISSUE TITLE
Can't start service after install and some else...

### ISSUE THREAD

**Issue by demosspro** [bondagit/aes67-linux-daemon#145]
Hello! Thanks for your job with aes67 technology!
i have the next issue - when i try to start daemon after daemon installation procedure i get the next error
[log.txt](https://github.com/bondagit/aes67-linux-daemon/files/13186883/log.txt)
second issue - How can I add an audio driver (ko) to always work on the system, even if I reboot it?
make -C /lib/modules/5.10.160-rockchip/build/ M=/root/aes67-linux-daemon/3rdparty/ravenna-alsa-lkm/driver modules_install
make[1]: Entering directory '/usr/src/linux-headers-5.10.160-rockchip'
  INSTALL /root/aes67-linux-daemon/3rdparty/ravenna-alsa-lkm/driver/MergingRavennaALSA.ko
  DEPMOD  5.10.160
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[1]: Leaving directory '/usr/src/linux-headers-5.10.160-rockchip'
After few minutes delays goes up

![2023-10-27_13-56-39](https://github.com/bondagit/aes67-linux-daemon/assets/47609764/0cc20f93-4943-4932-9903-dc6df9bd5acb)

have you any reccomendations to improve latency?
i use orange pi 5 8 core ( 4+4) i start daemon on 2 hi core on 2352MHz
player i start to 2 mid core on 2352 MHz with command
`root@ubuntu:~# taskset -c 4,5 mpg123 --loop 9999 -T -a plug:source_1 1.mp3`
To improve performance, I started the system with the isolspus=4,5,6,7 parameter and therefore the system does not affect programs that use these kernels (your daemon and player)
![2023-10-27_15-03-51](https://github.com/bondagit/aes67-linux-daemon/assets/47609764/1f97e894-2833-4c19-8d31-f935a2a707c2)

**Comment by bondagit** [comment]
check that you have TIC frame size @1FS (samples) at 1ms (48 frames)

**Comment by bondagit** [comment]
> i have the next issue - when i try to start daemon after daemon installation procedure i get the next error
> [log.txt](https://github.com/bondagit/aes67-linux-daemon/files/13186883/log.txt)

The daemon gets killed by systemd because it's not replying to heartbeats. 
You have to recompile it with the option -DWITH_SYSTEMD=ON . 
You can add this option at line 46 of the build.sh script. 
Once done you have to re-install the daemon.

**Comment by bondagit** [comment]
> second issue - How can I add an audio driver (ko) to always work on the system, even if I reboot it?

You can usally install the module using the following commands:

```
cd 3rdparty/ravenna-alsa-lkm/driver
sudo make modules_install
```
If this doesn't work because you miss kernel certificate follow the instructions at: [No OpenSSL sign-file signing_key.pem](https://superuser.com/questions/1214116/no-openssl-sign-file-signing-key-pem-leads-to-error-while-loading-kernel-modules)

Finally use the command to load the modules:

`sudo depmod -a`

**Comment by demosspro** [comment]
> check that

Yep - it is true
> You have to recompile it with the option -DWITH_SYSTEMD=ON .

May be add it by default to master branch?
> You can usally install the module using the following commands:

as i see - it is say me that 
> Warning: modules_install: **missing 'System.map'** file. Skipping depmod.

**Comment by bondagit** [comment]
> Warning: modules_install: missing 'System.map' file. Skipping depmod.
it's just a warning in process it should be completed

**Comment by demosspro** [comment]
> it's just a warning, the process should be successful

```
Ok, but it is not start automaticaly. .KO do not apply so i write the script 
echo performance > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy4/scaling_governor
echo performance > /sys/devices/system/cpu/cpufreq/policy6/scaling_governor
sudo sysctl -w net/ipv4/igmp_max_memberships=66
sysctl -w kernel.sched_rt_runtime_us=1000000
sudo sysctl -w kernel.perf_cpu_time_max_percent=0
sudo depmod -a
insmod /root/aes67-linux-daemon/3rdparty/ravenna-alsa-lkm/driver/MergingRavennaALSA.ko
sudo systemctl start aes67-daemon
```
2 stream channel have time-to-time problem with peak of packet loss ( 100-1200 ). So i am starting few tests now and try to tuning software

**Comment by bondagit** [comment]
> Ok, but it is not start automaticaly. .KO do not apply so i write the script

Yes, for auto loading do the following:

```
sudo sh -c  'echo MergingRavennaALSA > /etc/modules-load.d/MergingRavennaALSA.conf'
sudo sh -c  'echo MergingRavennaALSA >> /etc/modules'
```

This should work for distro with or without Systemd

**Comment by demosspro** [comment]
> This should work for distro with or without Systemd

i do that, than reboot system, wait a time - then check the service

```
Oct 30 08:17:23 ubuntu aes67-daemon[995]: [2023-10-30 08:17:23.679729] [0x0000ffff99c07040] [fatal]   driver_handler:: init open: >
Oct 30 08:17:23 ubuntu aes67-daemon[995]: [2023-10-30 08:17:23.679761] [0x0000ffff99c07040] [fatal]   Kernel module not loaded ?
Oct 30 08:17:23 ubuntu aes67-daemon[995]: [2023-10-30 08:17:23.679839] [0x0000ffff99c07040] [fatal]   main:: fatal exception error>
Oct 30 08:17:23 ubuntu aes67-daemon[995]: [2023-10-30 08:17:23.679846] [0x0000ffff99c07040] [info]    main:: end
Oct 30 08:17:23 ubuntu aes67-daemon[995]: daemon exiting with code: 1
Oct 30 08:17:23 ubuntu systemd[1]: aes67-daemon.service: Main process exited, code=exited, status=1/FAILURE

```

**Comment by bondagit** [comment]
> i try this config, but i think i do some mistakes in bindings?

I think it should be :
```
   bindings { 0 0 }
   bindings { 0 1 }
   bindings { 0 2 }

```

**Comment by demosspro** [comment]
Thanks! Do some stability test ( night ) - this is the result :) firsh 1.5 hours is good then random lost of  100-300 packets, then normal again. I'll try to find information on how to write detailed logs and figure out the problem with this. If you give any recommendations, I will try to implement them too. Are buffers needed somewhere in the configuration?
![2023-10-31_10-04-46](https://github.com/bondagit/aes67-linux-daemon/assets/47609764/3b514677-1d2f-453b-b179-4e0d2ac41cec) =480x
