### ISSUE TITLE
Instructions for simple setup

### ISSUE THREAD

**Issue by vicsavo** [bondagit/aes67-linux-daemon#146]
Hello,
I installed the aes67-linux-deamon to stream audio to a Mezzo AD amplifier [link](https://www.powersoft.com/en/products/install-amps/mezzo-series/mezzo-604-ad) . I'm using Ubuntu 20.04.
The software seems to run fine ( I can run run_test.sh and run_latency_test.sh ). I activated AES67 on the amplifier but I don't manage to find the device with the web GUI (I tried in "Sources", "Sinks" and "Browser") .  I verified with ping that the connection is working.
I'm not an audio expert and I'd like to know if you have instructions to make such simple setup work.
Thank you!
Carlo

**Comment by bondagit** [comment]
On the Linux host where the daemon is running you have an ALSA device card named RAVENNA that can be used to playback the Sources and record the Sinks. The binding between the RAVENNA devices and your Source and Stream channels is defined by your channel map. 
If you want to playback the Sources and the Sinks individually you have to use the ALSA plugins: see: https://github.com/bondagit/aes67-linux-daemon/issues/107

**Comment by keygee** [comment]
Hi,
You should enable aes67 on your powersoft amp via armonia plus app (by
powersoft) or by dante controller, then you can connect your previously
created source with the Linux Daemon to the mezzo amp.
Please verify to create your source in L24 format 48khz

Ciao

Guido

Il ven 17 nov 2023, 17:36 Andrea Bondavalli ***@***.***> ha
scritto:

**Comment by keygee** [comment]
Sorry I forgot to specify that the connection between AES67 Daemon and the
amplifier must be done using the Dante controller by audinate
Guido

Il ven 17 nov 2023, 18:30 Guido Caliandro ***@***.***> ha
scritto:

**Comment by vicsavo** [comment]
Thank you for your help!
I manage to do some steps ahead and as you can seen from the screenshot below I can see and connect the Mezzo AD amplifier and the source I created on the AES67 Daemon WebUI in the Dante Controller.

The ALSA source is configured correctly (L24 @ 48kHz).
AES67 is activated in the amplifier.

![image](https://github.com/bondagit/aes67-linux-daemon/assets/151197781/ce1dc82d-37e5-4e80-a598-4f544d139397)

 I tried to do a test with 
speaker-test -D plughw:RAVENNA -r 48000 -c 2 -t sine -F S24_3LE
but it didn't work.

I have some questions:
- Am I missing something?
- How can I configure ALSA/AES67 such that I have all the sources I need at start time? In my final configuration I will have 4 amplifiers (12 outputs) which I should be able to control independently.
- I tried to edit the file /etc/asound.conf adding 
pcm.source_1 {
    type dmix
    ipc_key 0x11111
    slave {
        pcm "hw:CARD=RAVENNA"
        channels 4
        rate 48000
        format S24_3LE
    }
    bindings { 0 0 1 1 }
}
but I didn't manage to make it work (I rebooted the system to be sure the modifications took place)

Thank you!
Carlo

**Comment by bondagit** [comment]
> I tried to do a test with
> speaker-test -D plughw:RAVENNA -r 48000 -c 2 -t sine -F S24_3LE
> but it didn't work.

what does it mean ? do you get an error ? 

> * I tried to edit the file /etc/asound.conf adding
>   pcm.source_1 {
>   type dmix
>   ipc_key 0x11111
>   slave {
>   pcm "hw:CARD=RAVENNA"
>   channels 4
>   rate 48000
>   format S24_3LE
>   }
>   bindings { 0 0 1 1 }
>   }
>   but I didn't manage to make it work (I rebooted the system to be sure the modifications took place)

what does it mean ? do you get an error ? what ALSA device do you use when you invoke the player ?

**Comment by vicsavo** [comment]
Hello,

> > I tried to do a test with
> > speaker-test -D plughw:RAVENNA -r 48000 -c 2 -t sine -F S24_3LE
> > but it didn't work.
> 
> what does it mean ? do you get an error ?

I don't get errors but the amplifier does not receive the stream (I checked this on the Armonia+ software from the producer).

> 
> > * I tried to edit the file /etc/asound.conf adding
> >   pcm.source_1 {
> >   type dmix
> >   ipc_key 0x11111
> >   slave {
> >   pcm "hw:CARD=RAVENNA"
> >   channels 4
> >   rate 48000
> >   format S24_3LE
> >   }
> >   bindings { 0 0 1 1 }
> >   }
> >   but I didn't manage to make it work (I rebooted the system to be sure the modifications took place)
> 
> what does it mean ? do you get an error ? what ALSA device do you use when you invoke the player ?

Also in this case the behavior is the same as in the above test. The device I used is plug:source_1.
Thanks
Carlo

**Comment by bondagit** [comment]
use a network sniffer and verify if you see the outgoing audo traffic from the Linux host where the daemon is running.

**Comment by keygee** [comment]
Hi,
The Dante devices listen to the multicast AES67 streams with IP 239.69.x.x,
sorry I forgot to specify.
Try to change the address of your source with an IP like 239.69.1.10 for
example.

Ciao

Guido


Il mer 22 nov 2023, 17:40 Andrea Bondavalli ***@***.***> ha
scritto:

**Comment by bondagit** [comment]
did it work ?

**Comment by vicsavo** [comment]
Hello, sorry if I didn't answer but I managed to test the suggestions only now. 
After changing the RTP base address to 239.69.1.10 as suggested by Guido it works!
Thank you for the help!
Just one last question. To configure the connection in the Dante Controller I created a source in the daemon WebUI.
After a PC restart the source disappears. 
Is there a way I can add the source permanently?
Carlo

**Comment by bondagit** [comment]
I guess your daemon is starting up automatically after a reboot.
The daemon persists the Sources and the Sinks configuration to a file. 
Check the "status_file" config parameter in the daemon configuration and make sure that such file is writable.

**Comment by vicsavo** [comment]
The file was not writable... Now it works
Thank you
Calro
