### ISSUE TITLE
Add RTP Sink > Better Error Handling?

### ISSUE THREAD

**Issue by Play-AV** [bondagit/aes67-linux-daemon#147]
Was re-doing a function to add an RTP sink via the REST API and noticed something.  If you're supplying an SDP string directly, you shouldn't need a 'source', yet without providing an empty string in the PUT request, it will fail with "failed to convert a number". Left me scratching my head for a few minutes until I checked the code in the daemon for handling errors, and went through and looked at my old function which does contain the empty {source: "" } in the final JSON for the body of the PUT req

Nothing major but might be worth a note somewhere, or a better error message, since the error message doesn't indicate what actually went wrong.

**Comment by bondagit** [comment]
can you provide an example of your PUT request ?

**Comment by bondagit** [comment]
yes, you are right, the "source" parameter is currently mandatory in the Add Sink request even if the "use_sdp" is set to false. Please leave it empty for the time being I will fix it with the next release.

**Comment by Play-AV** [comment]
> yes, you are right, the "source" parameter is currently mandatory in the Add Sink request even if the "use_sdp" is set to false. Please leave it empty for the time being I will fix it with the next release.

Yeah, it's nothing breaking or even urgent. Really the only thing I'd suggest is a note in the documentation since the error message doesn't communicate the problem in a meaningful way (since it complains about a number).

Dumb question, what happens if you supply an SDP string + a source URL? Does one invalidate the other?

**Comment by bondagit** [comment]
yes, both "source" and "sdp" are mandatory. "source" is only used when "use_sdp" = false and "sdp" is only used when "use_sdp" = true.  If you omit any of these you will get an error. I will change the documentation to reflect this.

**Comment by bondagit** [comment]
both "source" and "sdp" JSON parameters remain mandatory for a Sink but the error reporting has been improved.
