### ISSUE TITLE
Raspberry Pi  compatibility and performance

### ISSUE THREAD

**Issue by joerg-wille** [bondagit/aes67-linux-daemon#152]
(Sorry, did not find any other channel to ask questions?)
I would like to use a Raspberry Pi to stream 16 channel @96kHz audio in and out.
Is this at all possible with either Raspberry Pi 4 or 5 and if so, which latencies would be possible?
Also, I read that the public build of the [Merging driver](https://bitbucket.org/MergingTechnologies/ravenna-alsa-lkm/src/master/) is limited to 8 I/O - is this limitation still valid?

Raspberry Pi 5 adds support of Precision Time Protocol (PTP). Is PTP actually required or would it be beneficial for lower latencies?

Has anyone experience using the Merging driver with the [RT-Kernel](https://github.com/by/RT-Kernel)?

**Comment by Play-AV** [comment]
> @bondagit Thank you for answering all questions.

Did you end up getting 16ch on the Pi4 or Pi5?

**Comment by bondagit** [comment]
> Did you end up getting 16ch @96kHz on the Pi4 or Pi5?

I didn't test directly with any of them.
I tested it on a NanoPi NEO2 up to 24 channels @48Khz
