### ISSUE TITLE
Can Not Build on Ubuntu 22.04

### ISSUE THREAD

**Issue by ctecamp** [bondagit/aes67-linux-daemon#153]
Fails with the following.
Building aes67-daemon ...
-- The CXX compiler identification is Clang 14.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ - broken
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/tim/aes67-linux-daemon-master/daemon/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_606f6/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_606f6.dir/build.make CMakeFiles/cmTC_606f6.dir/build
    gmake[1]: Entering directory '/home/tim/aes67-linux-daemon-master/daemon/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_606f6.dir/testCXXCompiler.cxx.o
    /usr/bin/clang++    -MD -MT CMakeFiles/cmTC_606f6.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_606f6.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_606f6.dir/testCXXCompiler.cxx.o -c /home/tim/aes67-linux-daemon-master/daemon/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_606f6
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_606f6.dir/link.txt --verbose=1
    /usr/bin/clang++ CMakeFiles/cmTC_606f6.dir/testCXXCompiler.cxx.o -o cmTC_606f6 
    /usr/bin/ld: cannot find -lstdc++: No such file or directory
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    gmake[1]: *** [CMakeFiles/cmTC_606f6.dir/build.make:100: cmTC_606f6] Error 1
    gmake[1]: Leaving directory '/home/tim/aes67-linux-daemon-master/daemon/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_606f6/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

**Comment by bondagit** [comment]
It seems to be a problem with Ubuntu 22.04, please check:
https://stackoverflow.com/questions/74543715/usr-bin-ld-cannot-find-lstdc-no-such-file-or-directory-on-running-flutte

and try:
`sudo apt install libstdc++-12-dev`

**Comment by bondagit** [comment]
You can also try to compile using gcc instead of clang. To to this comment out the following two lines from build.sh:

```
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
```

**Comment by ctecamp** [comment]
Thanks I got it built.
Now just trying to interface this with a AES67 network.

Tim

**Comment by ctecamp** [comment]
Can't seem to get it to be stable.
I have a axia device running as master clock which the driver will locked
but unlocks frequently.
Also I have to reload the driver every time I reboot and the daemon times
out when I start it from systemctl.

I'm sure I'm missing something.

Tim
WZEW-FM
Mobile, Al.

**Comment by bondagit** [comment]
A patch has been recently added to transition the local PTP slave sync from  locked to unlocked in case the PTP master is not sending any announce after more than 5 seconds. 

Check if the driver is logging such message with:
`sudo dmesg | grep resetting`
E.g.:
`[8720383.161088] PTP Master announce timeout, resetting ...`

In this case it means your master is probably not sending announcements with a proper period or something is wrong in your setup.
In the driver you can change the timeout by changing the [define at line 50 in PTP.c](https://github.com/bondagit/ravenna-alsa-lkm/blob/6ca0a3d12fbdb91544c0ebde45d368c1fcd97270/driver/PTP.c#L56)

**Comment by bondagit** [comment]
Please make sure you follow the instructions at:
[systemd directory](https://github.com/bondagit/aes67-linux-daemon?tab=readme-ov-file#systemd-directory)
in particular make sure you have recompiled the daemon with the CMake option -DWITH_SYSTEMD=ON

**Comment by ctecamp** [comment]
Nevermind I got it.

Systems working as expected.

Thanks

Tim Camp
WZEW-FM
