### ISSUE TITLE
Multiple AES daemon?

### ISSUE THREAD

**Issue by ShadyHarbinger** [bondagit/aes67-linux-daemon#155]
Sorry for asking this here but I have not found any forum where I would have got help or advice.
I would like to capture a sink, upsample then send it to a source.
Because Sinks and Sources use the same PTP clock it cannot be done using one daemon so I am thinking of using two daemons.
One's sample rate would be set to the incoming stream (sink) and the other daemon's sample rate would be set to the outgoing (source)  sample rate. The point is to process an incoming stream with CamillaDSP and send the result to another AES67 network.

**Comment by bondagit** [comment]
There is no possibility to execute two daemons on the same host at the moment: the driver can work on a single network interface and there is single PTP slave configuration and a global sample rate.

**Comment by ShadyHarbinger** [comment]
Thank you for the clarification!
