### ISSUE TITLE
[Question] Can I run Dante-based multichannel setups (w/ Pipewire) ?

### ISSUE THREAD

**Issue by the-drunk-coder** [bondagit/aes67-linux-daemon#160]
Hi,  
I'll soon have the opportunity to play a multichannel (15ch) concert, and the venue uses Dante to drive their setup (not sure which products, exactly).

It's my first real-life contact with Dante, and while I know what it is in theory, I'm looking for a more practical perspective.

With this software, would I be able to just plug a network cable into my laptop, and address the individual channels, reliably enough to play a 30min concert? Or is there something that I'm missing?

I should probably also mention that I'm using Pipewire (with all the drop-in replacements for Alsa, Jack, etc).

Sorry if I'm spamming the bugtracker, I asked on LAU and it seems there's not much experience with Dante around there ...

Best,
N

**Comment by bondagit** [comment]
yes, you can try. 
Just make sure you run the daemon in real Linux box, no virtualised environments.
