### ISSUE TITLE
hard coded 44100hz

### ISSUE THREAD

**Issue by cloudcastsystemsau** [bondagit/aes67-linux-daemon#161]
hi @bondagit,

i've noticed in the timer process function when computing the tic count there is a hardcoded 44100.

```
 if(ui32R < 4 * self->m_ui32SamplingRate / 44100) // to avoid using timestamps outside 80us of theoretical time
            {
                ui64CurrentTICCount = ui64Q + 1; // we add 1 because ui64Q is the count for the previous frame
                //iTICCountUpdateMethod = 1;
            }
            else if(ui32R > self->m_ui32FrameSize - 4 * self->m_ui32SamplingRate / 44100)
            {
                ui64CurrentTICCount = ui64Q + 1 + 1; // we add 1 because ui64Q is the count for the previous frame
                //iTICCountUpdateMethod = 2;
            }
```

are you able to explain why there is a hardcoded 44100 which i assume is 44.1 khz?

**Comment by bondagit** [comment]
In that piece of code the next tick count is computed.
There is a tick every `TICFrameSizeAt1FS * ui32nFS / m_ui32SamplingRate.`  With _TICFrameSizeAt1FS = 48_ and _m_ui32SamplingRate = 48000_ -> _ui32nFS = 1_  we have a tick every  _1ms_ and _m_ui32FrameSize = 48_.
The next tick count is corrected depending on the offset from the PTP clock. 
 _ui64Q_ is the offset in number of frames (in number of 100us ticks) with _m_ui32FrameSize_ as frame size, while _ui32R_ is the rest of the previous division. 
The frame size _m_ui32FrameSize_ depends on the sample rate, see manager.c:355, so self->m_ui32SamplingRate / 44100 is used to get the frame size factor.
