### ISSUE TITLE
Only 2 channel audio device seen by Software

### ISSUE THREAD

**Issue by Trick17Industries** [bondagit/aes67-linux-daemon#172]
After getting the drivers and daemon built and stable on Ubuntu 18.04 (playback stability issues on 22.04) I have found that it only shows up as 2 channel io. I have confirmed that this io works cleanly with livewire AES67 source and livewire / dante outputs and the ALSA version on Stereotool in the middle. I want to receive and transmit multiple 2 channel streams with these drivers but cant work it out. 

In the daemon it list's 1-64ch in and out to map the sinks/sources to but if I add more sinks or sources than 1 they will clear on daemon restart.

aplay -l and arecord -l show the card with only one 1 sub device:
`user@ST11:/proc/asound/card1/pcm0c$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 7/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: RAVENNA [Merging RAVENNA], device 0: Merging RAVENNA [Merging RAVENNA]
  Subdevices: 0/1
  Subdevice #0: subdevice #0`

my system doesn't have a '/etc/asound.conf' file but that could be because Pluse was originally installed? and i dont mind if the OS has no audio device, just that the software can see the underlying ALSA devices..

the device is in '/proc/asound/' and looking around I can see the Sus0 device says it is only stereo:
`user@ST11:/proc/asound/card1/pcm0c/sub0$ cat hw_params
access: MMAP_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 48000 (48000/1)
period_size: 48
buffer_size: 2256`

Can I/How do get more than one stereo sink / source that will show as another selectable device in StereoTool?

**Comment by bondagit** [comment]
you are looking into the RAVENNA card capture device substream information and you have found that you have an open stereo capture on it. 
The RAVENNA is capable of capturing up to 64 channels and the Sink configuration determines the mapping between the Sink/ss and the ALSA channels.
