### ISSUE TITLE
How to configure the daemon?

### ISSUE THREAD

**Issue by skozlovski** [bondagit/aes67-linux-daemon#174]
Hi,
I have installed the daemon and it works, but I experience a quirk. I setup several sources, but I see only one Alsa sink that corresponds to all sources, it is called "RAVENNA". I also can not use this RAVENNA device in the  asoundrc  to create mixes, routes and soft volume. Is it the way this daemon works or I just not properly configuring it. Please offer some assistance if you can.  In reality, I would like each added to the daemon source to register it's own Alsa device and that I can use the device to create alsa soft volume plugins and routes through asoundrc.

Thanks,

**Comment by bondagit** [comment]
This is working configuration file for ALSA defining two separates sources and sinks by using proper ALSA plugins:
```
pcm.source_1 {
    type dmix
    ipc_key 0x11111
    slave {
        pcm "hw:CARD=RAVENNA"
        channels 4
        rate 48000
        format S24_3LE
    }
    bindings { 0 0 1 1 }
}

pcm.source_2 {
    type dmix
    ipc_key 0x11111
    slave {
        pcm "hw:CARD=RAVENNA"
        channels 4
        rate 48000
        format S24_3LE
    }
    bindings { 0 2 1 3 }
}

pcm.sink_1 {
    type dsnoop
    ipc_key 0x11111
    slave {
        pcm "hw:CARD=RAVENNA"
        channels 4
        rate 48000
        format S24_3LE
        buffer_size 4096
    }
    bindings { 0 0 1 1 }
}

pcm.sink_2 {
    type dsnoop
    ipc_key 0x11111
    slave {
        pcm "hw:CARD=RAVENNA"
        channels 4
        rate 48000
        format S24_3LE
        buffer_size 4096
    }
    bindings { 0 2 1 3 }
}

```
To be able to use the RAVENNA device for capturing make sure the Streamer is disabled.

**Comment by skozlovski** [comment]
Thank you. This did help and I was able to play a number of 64-ch audio files using the device without any errors using Alsa based player. However, without "buffer_size 4096" in the sources I get underruns. Adding buffer_size, fixed the problem and Alsa works great for me now.

Is it possible to configure Pulseaudio to use the RAVENNA as its sink. I have attempted to simple "pactl load-module" method and tried to play a file, but got an error on the receiver "failed! SDP invalid" (or something like that. Is there an example of how to setup pulseaudio?
Thanks,

**Comment by bondagit** [comment]
No I never used Pulseaudio with the daemon.
Also, I had problems with it in the past and my recommendation was to disable it.

**Comment by m7a** [comment]
The example by @bondagit helped me to get started with a customized ALSA config, too.

One thing I don't understand so far: How is the buffer_size to be defined? What unit does it have? It seems that many online sources suggest it is measured in bytes, but looking at the AES67 driver and the actual figures it seems as if it is rather measured in samples?

I don't run plain PulseAudio anymore, but got a variation of the config to work with Pipewire-Pulse (i.e. PulseAudio emulation provided by PipeWire).  My ALSA config is here: <https://github.com/m7a/lp-aes67-linux-daemon/blob/master/98-masysma-aes67.conf>. I plan to write a proper description on how it all fits together in my setup once I understand it myself :smile:

**Comment by bondagit** [comment]
In the Linux ALSA plugin, the parameter buffer_size is specified in frames, where each frame represents one sample for each channel. For example, if you have a stereo audio stream (2 channels), one frame would contain two samples (one for each channel).

**Comment by m7a** [comment]
> In the Linux ALSA plugin, the parameter buffer_size is specified in frames, where each frame represents one sample for each channel. For example, if you have a stereo audio stream (2 channels), one frame would contain two samples (one for each channel).

This makes perfect sense. Thank you very much for the clarification and help :)
