### ISSUE TITLE
module_timer.c: patch does not apply

### ISSUE THREAD

**Issue by hifi25nl** [bondagit/aes67-linux-daemon#18]
I have this problem:

Apply patches to ravenna-alsa-lkm module ...
error: patch failed: driver/module_timer.c:35
error: driver/module_timer.c: patch does not apply

**Comment by bondagit** [comment]
Hi there, the current patches applies to the revision [35c708f](https://bitbucket.org/MergingTechnologies/ravenna-alsa-lkm/commits/35c708f3747474130790cf508c064360a9589ac8) of the Ravenna driver and not to the current master branch (see [build.sh](build.sh) script) I will update the patches when I see important improvements.

**Comment by hifi25nl** [comment]
Ok, now is working with commit 35c708f
