### ISSUE TITLE
Cannot view in Dante Controller

### ISSUE THREAD

**Issue by josefhernandez** [bondagit/aes67-linux-daemon#22]
Hi,

I've modified the daemon.conf to include my ip and network interface, but Dante Controller cannot find my device after starting the daemon

```
{
  "http_port": 8080,
  "rtsp_port": 8854,
  "http_base_dir": "./webui/build",
  "log_severity": 8,
  "playout_delay": 0,
  "tic_frame_size_at_1fs": 192,
  "max_tic_frame_size": 1024,
  "sample_rate": 48000,
  "rtp_mcast_base": "239.1.0.1",
  "rtp_port": 5004,
  "ptp_domain": 0,
  "ptp_dscp": 48,
  "sap_interval": 30,
  "syslog_proto": "none",
  "syslog_server": "255.255.255.254:1234",
  "status_file": "./demo/status.json",
  "mdns_enabled": true,
  "interface_name": "enp11s0",
  "mac_addr": "a8:a1:59:18:f0:8c",
  "ip_addr": "192.168.0.10"
}
```

any tip?

**Comment by bondagit** [comment]
Hi there,
Did you create a daemon Source? 
The daemon announces the configured sources via SAP and the Dante Controller expects these multicast messages to show the sources in the Routing dialog.
See the guide [Devices and interoperability tests with the AES67 daemon](DEVICES.md)
If this doesn't work you have to verify whether your setup routes the multicast traffic properly.

**Comment by bondagit** [comment]
any news_ if not I would close the issue. Thanks

**Comment by josefhernandez** [comment]
Finally got it running with Dante. I need to add the following line, for the daemon to broadcast the SAP message in the right mutlicast address:

`"sap_mcast_addr": "239.255.255.255",`

**Comment by bondagit** [comment]
thanks for the update. What you added is the daemon default _sap_mcast_addr_ parameter.
I didn't notice it was not present in your config file.
