### ISSUE TITLE
Incorrect SAP packets TTL + patch

### ISSUE THREAD

**Issue by KT315A** [bondagit/aes67-linux-daemon#25]
Dear all,
The SAP udp packets are sent with ttl=1, which is usable for PC - cross-cable - PC only.

According to RFC2974, sap ttl should be 255, so here is a small patch;

Regards,
:+1:

**Comment by KT315A** [comment]
[diff.txt](https://github.com/bondagit/aes67-linux-daemon/files/5592852/diff.txt)

**Comment by bondagit** [comment]
it looks good to me. Thanks for the fix!
