### ISSUE TITLE
Not sure where sample rate is coming from...

### ISSUE THREAD

**Issue by Aika0** [bondagit/aes67-linux-daemon#27]
I'm sorry to ask something that is probably foolish, but I'm hoping you can help me.
I'm on a Raspberry Pi and have most everything working... but the sample rate appears to be reported based on audio in?
Is that what's happening?

When I create the source I set the following:
Max samples per packet to 48 - 1ms
Codec L24
Payload Type 98
TTL 14
DSCP 34 (AF41)
RefClk PTP traceable unchecked
Channels 2
Audio Channels map ALSA Output 1 ->ALSA Output 2

If I play a 48000 wav, I get the SAP saying 48000... if I play a 44100 wav I get the SAP saying 44100, regardless of output settings. Is the driver deducing the sample rate? Is there a way for me to force a specific sample rate regardless of input? I'd like to force 48000 to ensure AES67 compatibility even if the source is not truly 48000 or if there's no source at the moment.

Finally, I'm sorry to asking this here as an issue. I know it's really not, I just couldn't figure out how to ask a question.

**Comment by bondagit** [comment]
Hi there, 
no, your question is not foolish and you analysis is correct: the driver was originally thought to be able to dynamically switch the sample rate according to the playback or recording sample rate and it was never meant to perform any sample rate conversion.
Basically the idea is that when a new playback comes and the rate is different from the current or initial rate the driver informs the user space (the daemon) of this change and this in turn updates the advertised sources and switches the driver rate.
Note that I never needed this feature in my configuration either but I didn't want to change the original behavior.
If you just need 48KHz/L24 streams my suggestion is to use an ALSA plugin and let the plugin perform the necessary sample rate conversions.
So for example I can achieve this by using the DMIX plugin with the following ALSA configuration:

From file: _~/.asoundrc_
```
pcm.source_1 {
    type dmix
    ipc_key 0x11111
    slave {
        pcm "hw:1,0"
        channels 2
        rate 48000
        format S24_3LE
    }
    bindings { 0 0 1 1 }
}
```

And then I can playback a 44.1Khz file and let the plugin perfom the conversion to 48KHz with:

`aplay -D plug:source_1 sample.wav  -vv `

Use the option -vv In aplay to see the audio chain used to achieve this.

Finally, please note that I have found a bug in the daemon that currently does not always correctly set the new driver sample rate once the this has announced a change and I will be releasing a patch for this soon.

**Comment by bondagit** [comment]
Any update about this issue ? If it works for you I would close it. Thanks

**Comment by Aika0** [comment]
Yes... its working. Thanks for the super-quick reply. Sorry I didn't reply sooner.
I was thinking of trying to modify the driver to support a "lock" of the frequency to 48000Hz specifically for aes67 compatibility (since I think 48/24 is all it can be for aes67). I'm not sure it's necessary now though. It seems like now that I'm using ALSA to ensure things are 48000Hz I'm not having incorrect initial reporting. What do you think?

**Comment by bondagit** [comment]
My suggestion is to leave the driver as it is and to rely on the ALSA plugin to perform sample rate conversions.
You can always modify the driver to force a single sample rate but in that case all the attempts to playback or record at a different rate will fail with an error.
You you want to take this second direction just remove the undesired sample rate from the following structures in _3rdparty/ravenna-alsa-lkm/driver/audio_driver.c_

```
static struct snd_pcm_hardware mr_alsa_audio_pcm_hardware_capture
static struct snd_pcm_hardware mr_alsa_audio_pcm_hardware_playback
```
