### ISSUE TITLE
Unicast Support Possible?

### ISSUE THREAD

**Issue by stemcc** [bondagit/aes67-linux-daemon#30]
I'd love to start testing this in a studio environment currently running a medium-sized Dante network but which is completely unicast. I can't use multicast in this environment due to constraints outside of my control. 

Therefore I'm curious if you have plans for supporting unicast in addition to multicast. I'm not sure if the kernel module this is built upon requires multicast only.

**Comment by bondagit** [comment]
I did a quick test and can confirm that unicast streaming support is possible with changes to the user space only  (no need to patch the driver). Most of the changes would be to allow proper unicast streams configuration in the daemon and WebUI.

**Comment by keygee** [comment]
Hi Andrea!
It would be great!
Do you think you can dedicate time for this?
I wonder if Dante Controller could detect unicast AES67 streams.... never
tried...

cheers

Guido

Il giorno mer 27 gen 2021 alle ore 17:24 Andrea Bondavalli <
notifications@github.com> ha scritto:

**Comment by bondagit** [comment]
This is the next feature in the radar. I will post updates  about it on this issue.

**Comment by bondagit** [comment]
I will be releasing a beta version for this soon. The only limitation will be that the unicast IP address provided must be of an host connected to the same local network.

**Comment by bondagit** [comment]
hi @keygee and @stemcc ,
I have a first implementation that supports unicast destination addresses. 
Please checkout the [unicast_support branch](https://github.com/bondagit/aes67-linux-daemon/tree/unicast_support) and give it a try.
As already mentioned this works only for unicast destination addresses belonging to active host connected to the same local network.
If this is ok for you I will merge this back into the master branch.
Thanks.

**Comment by keygee** [comment]
Hi Andrea,
I successfully tested the unicast_support branch on my systems: everything works as expected, thank you for your great job.
Then I tried to send a stream from a daemon source to an audinate IP address of a Yamaha MTX5-D;
I could see the source, but no way to connect them (when I click on the connection square in Dante Controller, no icon appears....).
But maybe Dante does not support AES67 Unicast connection... I don't know... 
Thank you again for your work!

Work

**Comment by bondagit** [comment]
Hi Guido, thanks for confirming this. 
I tried myself with same results: Dante doesn't seem to support unicast addresses in AES67 mode for both rx and tx.
Also probably I should not advertise at all unicast sources with SAP and mDNS but at present I don't see any issue with this.

**Comment by bondagit** [comment]
I tested an unicast source using an [Hasseb device](http://hasseb.fi/shop2/index.php?route=product/product&product_id=62) and it works.

**Comment by bondagit** [comment]
Unicast support was merge into daemon master branch and daemon version changed to v1.1
