### ISSUE TITLE
Sound extremely distorted and crackling

### ISSUE THREAD

**Issue by jcelerier** [bondagit/aes67-linux-daemon#31]
Hello,
first thanks for the great project, it took us just a couple hours to connect our linux computer to Dante hardware (in our case an Allen & Heath dLive S7000). The linux computer acts as a source which plays back into two channels of the A&H for now.

However, the sound is fairly distorted: here is a recording of what we hear when running 

```
$ speaker-test -F S32_LE -D plughw:RAVENNA -r 48000 -c 2 -t sine
$ speaker-test -F S32_LE -D plughw:RAVENNA -r 48000 -c 2 -t pink
```
[recorded.zip](https://github.com/bondagit/aes67-linux-daemon/files/5888436/recorded.zip)

Here is the config:
```
{
  "http_port": 8080,
  "rtsp_port": 8854,
  "http_base_dir": "./webui/build",
  "log_severity": 3,
  "playout_delay": 0,
  "tic_frame_size_at_1fs": 48,
  "max_tic_frame_size": 1024,
  "sample_rate": 48000,
  "rtp_mcast_base": "239.69.0.1",
  "rtp_port": 5004,
  "ptp_domain": 0,
  "ptp_dscp": 48,
  "sap_mcast_addr": "239.255.255.255",
  "sap_interval": 30,
  "syslog_proto": "none",
  "syslog_server": "255.255.255.254:1234",
  "status_file": "./demo/status.json",
  "interface_name": "enp61s0",
  "mdns_enabled": true,
  "mac_addr": "00:00:00:00:00:00",
  "ip_addr": "169.254.13.210",
  "node_id": "AES67 daemon 007f0100"
}
```

and the status:
```
{
  "sources": [
  {
    "id": 0,
    "enabled": true,
    "name": "ALSA Source 0",
    "io": "Audio Device",
    "max_samples_per_packet": 48,
    "codec": "L24",
    "ttl": 15,
    "payload_type": 98,
    "dscp": 46,
    "refclk_ptp_traceable": false,
    "map": [ 0, 1 ]
  }  ],
  "sinks": [  ]
}
```

we don't know what to tweak to make it work :(

thanks !

**Comment by jcelerier** [comment]
Also, an observation : it seems that adding more channels in the source changes the sound (by a fair amount), which makes me wonder if there is not something in the chain that interprets the number of channels incorrectly ? I suspected the RAVENNA driver but cannot find how it is configured.

**Comment by bondagit** [comment]
Hi there, your daemon configuration looks ok. 
Are you using a VM ? Is this is the case it is a bad idea because you cannot achieve the latency level you configured (1ms). 
Instead of attaching mp3 audio file it's better to use an application like GoldWave to analyses the recording. This could provide you some more info about the problem you have.

**Comment by jcelerier** [comment]
Also the clock showed up as "slave" and "locked" in the web ui, which I assume are the correct thing to see.

**Comment by bondagit** [comment]
Any news about this problem ?

**Comment by jcelerier** [comment]
no sorry, I only have access to the AES system once in a while, next time may not be before a copule weeks :/

**Comment by moonshaadow** [comment]
Maybe you should try at 96kHz ?
The A&H Dante card is given for 48 and 96, but dLive S7000 is 96 only. If I'm not wrong, the conversion is not automatic, you have to set up the Dante card to 48kHz to be able to use it with 48k signal. The dLive will do the conversion.
This is, I believe, the recommendation to use with other Dante stuff : [A&H forum](https://community.allen-heath.com/forums/topic/48k-96k-dante-sync/#post-83803)

**Comment by jcelerier** [comment]
Hello,

yes, yesterday we went to the company who built the audio system for that concert place and tested with other aes67 hardware and they told us the same, that we should try on 96k. The driver worked perfectly on this other hardware so I think we can safely close that issue. Thanks and sorry for the noise !
