### ISSUE TITLE
Version Information

### ISSUE THREAD

**Issue by Aika0** [bondagit/aes67-linux-daemon#32]
Hi,

Do you think you could add a command line parameter to print a version number and exit... something like -v or --version?
That way we could compare versions to know if we're running an obsolete version of the daemon?

Also, I don't know if this is possible, but maybe you could also patch the kernel driver to indicate the version of the daemon it's supposed to be run against? Currently modinfo returns a version of 0.2 (which I assume is the Merging Tech version number). Since you're modifying it with patches, maybe it could say 0.2-x.x.x (where x.x.x is the daemon version) or something?

Hardly essential, but would be helpful to track versions running.

Thanks again for the great project!

Alexa

**Comment by bondagit** [comment]
Hi Alexa, it sounds reasonable.
What about using the abbreviated git repo hash as version or version extension for both? 
This way it's super easy to associate the binaries to the sources. 
Consider that fortunately I have never changed the driver interface so the daemon is always compatible with an old driver and v.v. and so there is no need to check for incompatibilities.

**Comment by bondagit** [comment]
I am working to reach version 1.0 that will come with a simple test suite to validate the platform one is going to use. 
I will start handling the versioning from that point on.

**Comment by Aika0** [comment]
Awesome, thank you!

**Comment by bondagit** [comment]
I set the version of the ALSA Ravenna kernel module to _bondagit-1.0_ and added tag v1.0 to the module repo. 
https://github.com/bondagit/ravenna-alsa-lkm/releases/tag/v1.0
I have also changed the daemon to return the current version set to _bondagit-1.0_  and added tag v1.0 to the daemon repo. 
https://github.com/bondagit/aes67-linux-daemon/releases/tag/v1.0
I will update the version info when new changes come.
