### ISSUE TITLE
disk space

### ISSUE THREAD

**Issue by antonellocaroli** [bondagit/aes67-linux-daemon#39]
question, maybe stupid.
Once compiled, the directory takes up about 260MB of disk space.
The question is:
Is there anything that takes up a lot of space that can be deleted?of unnecessary?

**Comment by bondagit** [comment]
Hello,
most of the disk space usage comes from the C++ and React WebUI compilation artifacs.
We also have a few megabytes from the wavplay_am824 audio test files.

But when it comes to delivery / install the AES67 daemon the only files needed are the following:
```
daemon/aes67-daemon  (daemon binary)
daemon/daemon.conf (daemon configuration file)
3rdparty/ravenna-alsa-lkm/driver/MergingRavennaALSA.ko (ALSA driver)
webui/build/ (webui files)
```
And the binaries can be stripped, so you just require a few MB in the end.

**Comment by bondagit** [comment]
I saved some disk space by removing some wav test files that are easy to create using sox.
Most of the disk space is used by compilation artifcats.
