### ISSUE TITLE
WebUI is white and dante controller does not detect anything

### ISSUE THREAD

**Issue by GrosRems** [bondagit/aes67-linux-daemon#48]
Hello

I am trying to test aes67-daemon on a raspberry pi 4 but I have two problems:

1- If I run the daemon with the production configuration file, the WebUI returns a blank page (the source is empty). But, whith a test configuration file (edited to use the ethernet interface), the WebUI works correctly.

2- Whatever the configuration file used, Dante Controller does not show this device.

I think I followed the commissioning steps precisely, I am not at all an expert on Linux, however I am used to Dante and therefore to the network in general.

Can you get me some help?

thank you so much

**Comment by GrosRems** [comment]
I'm sorry, I tried a lot of things for 2 days before asking for help. I ended up realizing that the web page was blank because I was not in the correct folder, I started the daemon "from afar". Once the functional WebUI I could see that by default no source is created, thereafter everything works fine.

**Comment by anbraten** [comment]
@GrosRems Your first question probably came from the network interface only be listening to `localhost`. It has to be changed to some proper network-interface as the daemon is only listening at one interface at the time.

```diff
{
  "http_port": 8080,
  "rtsp_port": 8854,
  "http_base_dir": "../webui/dist",
  "log_severity": 2,
  "playout_delay": 0,
  "tic_frame_size_at_1fs": 64,
  "max_tic_frame_size": 1024,
  "sample_rate": 48000,
  "rtp_mcast_base": "239.1.0.1",
  "rtp_port": 5004,
  "ptp_domain": 0,
  "ptp_dscp": 48,
  "sap_mcast_addr": "239.255.255.255",
  "sap_interval": 30,
  "syslog_proto": "none",
  "syslog_server": "255.255.255.254:1234",
  "status_file": "./status.json",
  "mdns_enabled": true,
-  "interface_name": "lo"
+ "interface_name": "eth0"
}
```

For the second problem: If you followed each step from the [Devices and interoperability tests](https://github.com/bondagit/aes67-linux-daemon/blob/master/DEVICES.md) docs, you could try this [AES67 Monitor](https://github.com/philhartung/aes67-monitor) on a separate computer in the network. That tool helped me a lot.

**Comment by anbraten** [comment]
> I'm sorry, I tried a lot of things for 2 days before asking for help. I ended up realizing that the web page was blank because I was not in the correct folder, I started the daemon "from afar". Once the functional WebUI I could see that by default no source is created, thereafter everything works fine.

Sometimes it's so simple to resolve 😉 . Glad you found the problem.

**Comment by GrosRems** [comment]
Thanks for trying to help me

**Comment by RyanMelenaNoesis** [comment]
I had this happen when I was running `aes67-daemon` from a directory other than `daemon`.  Imagine it has to do with the default daemon.conf containing relative paths.
