### ISSUE TITLE
Daemon fails to parse AVIO SDP file

### ISSUE THREAD

**Issue by keygee** [bondagit/aes67-linux-daemon#5]
Hi Andrea,
I'm trying to receive a stream from an Audinate Dante AVIO USB with the Daemon, but it fails.
After creating the Multicast flow with the Dante Controller, I can see it on the Browser page of the daemon, this is its info:

v=0
o=- 1415370 1415370 IN IP4 192.168.1.81
s=AVIOUSB-503633 : 2
c=IN IP4 239.69.251.175/32
t=0 0
a=keywds:Dante
m=audio 5004 RTP/AVP 97
i=2 channels: Left Right
a=recvonly
a=rtpmap:97 L24/48000/2
a=ptime:1
a=ts-refclk:ptp=IEEE1588-2008:00-1D-C1-FF-FE-50-36-33:0
a=mediaclk:direct=2911906980

but when I try to add it as a sink, I receive an HTTP  400 error.

Please tell me if you need more info or tests

Thank you for your really nice work

Guido

**Comment by bondagit** [comment]
Hi Guido,
thanks a lot for finding this issue and for the details.
I have created a new branch with a tentative fix for this issue, see:
[fix-parse-avio-sdp-file](https://github.com/bondagit/aes67-linux-daemon/tree/fix-parse-avio-sdp-file)
I can parse the file you provided here and extract the relevant info.
Can you give this a try ?
If confirmed working your side I will merge this into the master branch.
Andrea

**Comment by keygee** [comment]
Hi Andrea,
with the new branch, I've successfully added the sink of the AVIO stream into the daemon, and I can hear it via the MergingRavennaALSA module.
Thank you very much for your great work
Guido

**Comment by bondagit** [comment]
Hi Guido, 
thanks for your feedback. 
I will close this issue. 
Andrea
