### ISSUE TITLE
Browse and duplicate SAP message

### ISSUE THREAD

**Issue by calanor** [bondagit/aes67-linux-daemon#50]
I have a machine that sends a duplicate SAP packet.
Every 30 seconds I receive 2 identical SAP messages but it is discarded by timeout (browser.cpp: 125) because "announce_period" is 0 due to browser.cpp: 103  operation.

Other SAP browsers correctly display the message with this duplication.

A possible solution is not replace the source (browser.cpp: 105) if  "upd_source.announce_period" is 0. 

Look at the SAP message 42097 in the following log fragment (  09:45:02  and  09:45:09 )

> 
> [2021-09-27 09:44:57.804330] [0x00007fbf7600e700] [info]    driver_manager:: cmd GetPTPConfig done data len 2
> [2021-09-27 09:44:57.804372] [0x00007fbf7600e700] [debug]   driver_manager:: PTP Domain 0 DSCP 46
> [2021-09-27 09:44:57.804413] [0x00007fbf7600e700] [debug]   driver_handler:: sending command code 32 data len 0
> [2021-09-27 09:44:57.804480] [0x00007fbf7600e700] [debug]   driver_handler:: command code 32 data len 0 sent
> [2021-09-27 09:44:57.804599] [0x00007fbf7600e700] [debug]   driver_handler:: received cmd code 32 error 0 data len 16
> [2021-09-27 09:44:57.804649] [0x00007fbf7600e700] [info]    driver_manager:: cmd GetPTPStatus done data len 16
> [2021-09-27 09:44:57.804692] [0x00007fbf7600e700] [debug]   driver_manager:: PTP Status locked GMID 2461537149931028488 Jitter 0
> [2021-09-27 09:44:58.805124] [0x00007fbf7600e700] [info]    sap::announcement c8e3
> [2021-09-27 09:44:58.805405] [0x00007fbf7600e700] [info]    session_manager:: next SAP announcements in 30 secs
> [2021-09-27 09:45:02.086407] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:33583
> [2021-09-27 09:45:02.086506] [0x00007fbf67fff700] [debug]   browser:: refreshing SAP source sap:33583
> [2021-09-27 09:45:02.902596] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:**42097**
> [2021-09-27 09:45:02.903870] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:**42097**
> [2021-09-27 09:45:02.903970] [0x00007fbf67fff700] [debug]   browser:: refreshing SAP source sap:**42097**
> [2021-09-27 09:45:07.592673] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:22274
> [2021-09-27 09:45:07.592776] [0x00007fbf67fff700] [debug]   browser:: refreshing SAP source sap:22274
> [2021-09-27 09:45:07.593015] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:28447
> [2021-09-27 09:45:07.593094] [0x00007fbf67fff700] [debug]   browser:: refreshing SAP source sap:28447
> [2021-09-27 09:45:07.593327] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:63533
> [2021-09-27 09:45:07.593402] [0x00007fbf67fff700] [debug]   browser:: refreshing SAP source sap:63533
> [2021-09-27 09:45:07.593610] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:55606
> [2021-09-27 09:45:07.593669] [0x00007fbf67fff700] [debug]   browser:: refreshing SAP source sap:55606
> [2021-09-27 09:45:07.593830] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:36957
> [2021-09-27 09:45:07.593887] [0x00007fbf67fff700] [debug]   browser:: refreshing SAP source sap:36957
> [2021-09-27 09:45:07.594040] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:20166
> [2021-09-27 09:45:07.594116] [0x00007fbf67fff700] [debug]   browser:: refreshing SAP source sap:20166
> [2021-09-27 09:45:07.594269] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:5352
> [2021-09-27 09:45:07.594318] [0x00007fbf67fff700] [debug]   browser:: refreshing SAP source sap:5352
> [2021-09-27 09:45:07.594463] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:36087
> [2021-09-27 09:45:07.594510] [0x00007fbf67fff700] [debug]   browser:: refreshing SAP source sap:36087
> [2021-09-27 09:45:07.594683] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:7935
> [2021-09-27 09:45:07.594731] [0x00007fbf67fff700] [debug]   browser:: refreshing SAP source sap:7935
> [2021-09-27 09:45:07.807976] [0x00007fbf7600e700] [debug]   driver_handler:: sending command code 31 data len 0
> [2021-09-27 09:45:07.808116] [0x00007fbf7600e700] [debug]   driver_handler:: command code 31 data len 0 sent
> [2021-09-27 09:45:07.808325] [0x00007fbf7600e700] [debug]   driver_handler:: received cmd code 31 error 0 data len 2
> [2021-09-27 09:45:07.808409] [0x00007fbf7600e700] [info]    driver_manager:: cmd GetPTPConfig done data len 2
> [2021-09-27 09:45:07.808477] [0x00007fbf7600e700] [debug]   driver_manager:: PTP Domain 0 DSCP 46
> [2021-09-27 09:45:07.808523] [0x00007fbf7600e700] [debug]   driver_handler:: sending command code 32 data len 0
> [2021-09-27 09:45:07.808590] [0x00007fbf7600e700] [debug]   driver_handler:: command code 32 data len 0 sent
> [2021-09-27 09:45:07.808703] [0x00007fbf7600e700] [debug]   driver_handler:: received cmd code 32 error 0 data len 16
> [2021-09-27 09:45:07.808757] [0x00007fbf7600e700] [info]    driver_manager:: cmd GetPTPStatus done data len 16
> [2021-09-27 09:45:07.808808] [0x00007fbf7600e700] [debug]   driver_manager:: PTP Status locked GMID 2461537149931028488 Jitter 0
> [2021-09-27 09:45:07.883909] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:16888
> [2021-09-27 09:45:07.884003] [0x00007fbf67fff700] [debug]   browser:: refreshing SAP source sap:16888
> [2021-09-27 09:45:09.884847] [0x00007fbf67fff700] [info]    browser:: SAP source sap:**42097** timeout
> [2021-09-27 09:45:15.731765] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:60006
> [2021-09-27 09:45:15.731916] [0x00007fbf67fff700] [debug]   browser:: refreshing SAP source sap:60006
> [2021-09-27 09:45:16.675872] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:61283
> [2021-09-27 09:45:16.676005] [0x00007fbf67fff700] [debug]   browser:: refreshing SAP source sap:61283
> [2021-09-27 09:45:16.989996] [0x00007fbf67fff700] [debug]   browser:: received SAP message for sap:4756
> [2021-09-27 09:45:16.990096] [0x00007fbf67fff700] [debug]   browser:: refreshing SAP source sap:4756
>

**Comment by bondagit** [comment]
> A possible solution is not replace the source  (browser.cpp: 105) if "upd_source.announce_period" is 0.

I would rather not update the announce period if two packets from the same source arrive in less than a second. This should prevent setting an announce period of 0.

**Comment by bondagit** [comment]
@calanor I pushed the proposed changes to [issue-50](https://github.com/bondagit/aes67-linux-daemon/tree/issue-50) branch. 
Can you test it with your setup ? 
If that works I will change the daemon release and merge the modifications to master.
Thanks.

**Comment by calanor** [comment]
Your patch works perfectly.
Thanks

**Comment by bondagit** [comment]
can you checkout the master branch (v1.3) and check that everything is still ok ? 
Thanks

**Comment by calanor** [comment]
Yes, work fine with the v1.3 branch (e12d160)

**Comment by bondagit** [comment]
Good. Thanks.
