### ISSUE TITLE
Update sap in browse when verskon change

### ISSUE THREAD

**Issue by calanor** [bondagit/aes67-linux-daemon#56]
When sdp its updated and change the version number, the sap browse don't update the sdp.
is the sess-version and is on the line that starts with "o=" line  (https://datatracker.ietf.org/doc/html/rfc4566#section-5.2)

You could save the value in RemoteSource struct and detect when the version value changes. You should also take into sess-id and IP address of the machine from which the  session was created.  In case any of these values were modified, it would be necessary to refresh the sdp  according to the RFC.

**Comment by bondagit** [comment]
The daemon supports remote sources SDP updates via SAP as described by: https://datatracker.ietf.org/doc/html/rfc2974#section-5
Basically in case an SDP file gets updated a SAP deletion for the old Source is sent and a new announcement is sent.
The daemon also supports remote sources SDP updated via RTSP ANNOUNCE

**Comment by calanor** [comment]
Ok, but in this case when modify a SAP msg_id_hash in browse appears as a new SAP message duplicating the other until it is discarded by period expiration.   Other option its modify the sdp  of SAP message in browser when sess-version of sdp its modified.

**Comment by bondagit** [comment]
No, because in case the SDP file gets updated a deletion for the previous session plus a new announcement  should be sent:
```
   Message Identifier Hash. A 16 bit quantity that, used in combination
      with the originating source, provides a globally unique identifier
      indicating the precise version of this announcement.  The choice
      of value for this field is not specified here, except that it MUST
      be unique for each session announced by a particular SAP announcer
      and it MUST be changed if the session description is modified (and
      a session deletion message SHOULD be sent for the old version of
      the session).
```
