### ISSUE TITLE
warning:   rtsp_client:: unable to connect to ...

### ISSUE THREAD

**Issue by calanor** [bondagit/aes67-linux-daemon#57]
The daemon returns this warning when starting:
`[2021-12-22 08:57:30.718098] [0x00007f2b27fff700] [warning] rtsp_client:: unable to connect to 172.31.10.101:8854`

It seems that the problem is related to the IP associated with the wrong interface.
In my case I have two interfaces. eth0 for control use and eth1 connected to the audio network and for use for all services related to audio IP.
From what you see in the error it is using the IP associated with eth0 (172.31.10.10)  instead of the IP associated with eth1 interface (10.100.1.41).

I have also observed that the browse does not show any rtsp annunces and that on other machines receive the rtsp from this daemon  with the ip of eth0 instead of eth1.

In daemon.conf I have "eth1" correctly set in "interface_name", and SAP works correctly.

**Comment by bondagit** [comment]
The daemon uses Avahi to detect remote mDNS sources and then it tries to connect to the  RTSP address and port specified in the mDNS record to fetch the associated SDP file.
Unfortunately it's not possible to program Avahi in order to report remote sources connected to a specific interface only, see athiat/avahi/issues#168
Is your remote Source properly announced on the subnet 10.0.0.0/8 ?
Try if you see it with: 
 `avahi-browse -r _ravenna_session._sub._rtsp._tcp`

**Comment by calanor** [comment]
avahi-browse receive all announces from 10.100.0.0/16 except the sources of self machine aes67-linux-daemon and sources for other identical machine with double interface in the same subnets running also a aes67-linux-daemon.

See the avahi-browse output fragment. The eht0 are one form localhost and the other from a second machine:

```
+   eth1 IPv4 LAWO_N73_AS5P1_013                                               RTSP Realtime Streaming Server local
+   eth1 IPv4 LAWO_N73_AS5P1_014                                               RTSP Realtime Streaming Server local
+   eth1 IPv4 LAWO_N73_AS5P1_012                                               RTSP Realtime Streaming Server local
+   eth1 IPv4 LAWO_N73_AS5P1_015                                               RTSP Realtime Streaming Server local
+   eth1 IPv4 LAWO_N73_AS5P1_016                                               RTSP Realtime Streaming Server local
+   eth0 IPv4 AES67 daemon 2e0a1164 SIP LNX 1282-1285                          RTSP Realtime Streaming Server local
+   eth0 IPv4 AES67 daemon 2e0a1464 LNX SIP 57-64                              RTSP Realtime Streaming Server local
+   eth0 IPv4 AES67 daemon 2e0a1464 LNX SIP 9-16                               RTSP Realtime Streaming Server local
+   eth1 IPv4 VMIX1_BUS1                                                       RTSP Realtime Streaming Server local
+   eth1 IPv4 VMIX1_BUS2                                                       RTSP Realtime Streaming Server local
+   eth1 IPv4 VMIX1_BUS3                                                       RTSP Realtime Streaming Server local
+   eth1 IPv4 VMIX1_BUS4                                                       RTSP Realtime Streaming Server local
+   eth1 IPv4 ANUBIS_CH2                                                       RTSP Realtime Streaming Server local
```
l

**Comment by bondagit** [comment]
If you use option -r you can also see the IP address and port of the remote source.

ok, so regarding the problem:

`[2021-12-22 08:57:30.718098] [0x00007f2b27fff700] [warning] rtsp_client:: unable to connect to 172.31.10.101:8854`

can you try to execute the following:

`nc 172.31.10.101 8854`

**Comment by calanor** [comment]
Yes. The IP address corresponds to its interface eth0, 172.31.10.10 in one case and 172.31.10.12 in the other.  Other machines on  10.0.0.0 subnet can not access via 172.31.0.0/16 subnet.

**Comment by calanor** [comment]
Likewise, I do not understand what the warning message is due to when starting. The rtsp_client does not receive anounces rtsp,

**Comment by bondagit** [comment]
The daemon uses Avahi to browse the remote sources and tries to connect to the Avahi browser provided remote IP via RTSP to fetch the SDP file, hence the error you see.

**Comment by calanor** [comment]
It is that I have a strange behavior that I do not know if it is normal.
I have four interfaces ( lo, eth0, eth1 and docker0 ).  
The function get_interface_name from interface.cpp return always 2. 
I uncomented the  debug line and test with all interfaces in daemon.conf:
```

[2021-12-28 13:31:31.352602] [0x00007f2f59aff4c0] [debug]    interface eth1 index 2
[2021-12-28 13:31:54.449510] [0x00007f583282b4c0] [debug]    interface eth0 index 2
[2021-12-28 13:32:07.411505] [0x00007f00438d84c0] [debug]    interface lo index 2
[2021-12-28 13:32:48.004261] [0x00007f26d01774c0] [debug]    interface docker0 index 2
```

**Comment by calanor** [comment]
Changing SIOCGIFADDR  by SIOCGIFINDEX  shows a mDNS sources in browse. Until now they only appeared of the SAP type.
But, I receive a lot of error 400 getting self sources:

```
[2021-12-28 14:18:29.289118] [0x00007f0869c9b700] [error]   rtsp_server:: CSeq not specified from 10.100.1.43:58888
[2021-12-28 14:18:29.289232] [0x00007f0869c9b700] [error]   rtsp_server:: GET /by-name/AES67%20daemon%202e0a1464%20LNX%20SIP%2017-24 HTTP/1.1 response 400 to 10.100.1.43:58888
[2021-12-28 14:18:29.516267] [0x00007f0869c9b700] [error]   rtsp_server:: CSeq not specified from10.100.1.42:47839
[2021-12-28 14:18:29.516378] [0x00007f0869c9b700] [error]   rtsp_server:: GET /by-name/AES67%20daemon%202e0a1464%20LNX%20SIP%2017-24 HTTP/1.1 response 400 to 10.100.1.42:47839
[2021-12-28 14:18:30.526048] [0x00007f0869c9b700] [error]   rtsp_server:: CSeq not specified from 10.100.1,48:38012
[2021-12-28 14:18:30.526157] [0x00007f0869c9b700] [error]   rtsp_server:: GET /by-name/AES67%20daemon%202e0a1464%20LNX%20SIP%2017-24 HTTP/1.1 response 400 to 10.100.1.48:38012
[2021-12-28 14:18:30.559514] [0x00007f0869c9b700] [error]   rtsp_server:: CSeq not specified from 10.100.1.47:59424
[2021-12-28 14:18:30.559621] [0x00007f0869c9b700] [error]   rtsp_server:: GET /by-name/AES67%20daemon%202e0a1464%20LNX%20SIP%2017-24 HTTP/1.1 response 400 to 10.100.1.47:59424

```

**Comment by calanor** [comment]
With this patch, the rtsp connection warning disappears and the mDNS sources appear in the browser. Until now, the browser only showed sources from SAP.
https://gist.github.com/calanor/88f572714b5da25deb87fbda99062a52

**Comment by bondagit** [comment]
Good, thanks.
Can you push the changes to the issue-57 branch and issue a merge request?

**Comment by bondagit** [comment]
thanks for the fix!
