### ISSUE TITLE
aes67-daemon-receiver drops out ofter several hours

### ISSUE THREAD

**Issue by steeley** [bondagit/aes67-linux-daemon#58]
Been seeing this issue , related to my post here:
https://github.com/bondagit/aes67-linux-daemon/issues/53#issuecomment-986214403

setup: Raspberry pi cm4 module:  AES67-deamon =player. Another identical system but just running AES67-daemon as a receiver.
the alsaloop method has small dropouts and sync jumps, the gstreamer method was slightly better.
What seems to happen is the latency increases very slowly and then after about 4-8hours the receiver has stopped playing, but appears to have  no errors.

As a control test I used a Dante USB adapter in AES67 mode as a receiver on my Macbook. This seemed ok and was still receiving audio from the aes67-daemon player.

**Comment by bondagit** [comment]
Thanks for sharing this.
In alsaloop you can try with the options:
`-A 0 -n  -S samplerate`
This should enable the resampling via the libsamplerate.so

**Comment by steeley** [comment]
`-A 0 -n -S samplerate`

just says there is no samplerate support

**Comment by bondagit** [comment]
it works for me. Check your distribution or recompile the _alsa-utils_ separately after installing the libsamplerate:

    sudo apt-get install libsamplerate-dev

**Comment by steeley** [comment]
Ok that looks like a solution.
