### ISSUE TITLE
Sample rate in source SDP is incorrect

### ISSUE THREAD

**Issue by steeley** [bondagit/aes67-linux-daemon#61]
When setting a new source, the sample rate in the SDP is 44100 even though the config page is set to 48000.
The generated stream does appear to be 48k though.
daemon.conf does have 48000 shown as default.

**Comment by bondagit** [comment]
See issue #27

**Comment by steeley** [comment]
ok, I'm using pulseaudio now and it seems to work ok with that, which is set to default to 48k.
