### ISSUE TITLE
Not sending any PTP packets

### ISSUE THREAD

**Issue by llamafilm** [bondagit/aes67-linux-daemon#63]
Hello and thank you for this very cool piece of software.  I have it running on Ubuntu with a sink and a source, and both are working okay.  However, I noticed this app never sends any PTP `Delay_Req` packets, so it has no way to know if it's in sync.  The webpage shows it's locked as a slave with the correct GMID, and the delta never changes from zero, so I suppose you just read the PTP `Announce` packets and assume sync is perfect?
I can see this by running `tcpdump -i ens224 -n "(port 319 || port 320 || port 9875) && src 10.49.51.185"` (where 185 is the only IP of this machine).  This shows SAP packets correctly on port 9875 but nothing on the PTP ports 319 or 320.  I also checked on the `lo` interface and it's not there either.

<img width="352" alt="Screen Shot 2022-01-17 at 15 38 38" src="https://user-images.githubusercontent.com/3991046/149847969-dbb32521-76d0-4a48-b6cb-cfa5201f1272.png">

**Comment by llamafilm** [comment]
Looking into this further, I guess it's an upstream problem.  The `GetPTPStats` method is commented out.
https://bitbucket.org/MergingTechnologies/ravenna-alsa-lkm/src/master/driver/PTP.c#lines-1193

Have you noticed any clock issues from this?

**Comment by bondagit** [comment]
yes, I am aware of this as I had a look to the driver PTP code in the past.

FYI the daemon is currently using the [aes67-daemon branch](https://github.com/bondagit/ravenna-alsa-lkm/tree/aes67-daemon) of the bondagit/ravenna-alsa-lkm repository for the driver where I pushed a bunch of fixes for it, see [3rd party](https://github.com/bondagit/aes67-linux-daemon#3rdparty-directory) in the daemon documentation.

Thought the driver implements the sendDelayReq() in PTP.c ([PTP.c#L784](https://github.com/bondagit/ravenna-alsa-lkm/blob/master/driver/PTP.c#L784)) is currently not used ([PTP.c#L537](https://github.com/bondagit/ravenna-alsa-lkm/blob/master/driver/PTP.c#L537)) and the processing of the delay response message is not implemented at all ([PTP.c#L544](https://github.com/bondagit/ravenna-alsa-lkm/blob/master/driver/PTP.c#L544)).

So the synchronisation is currently based on PTP sync and follow up messages only but I didn't notice any issue directly related to this.

**Comment by llamafilm** [comment]
I'm surprised there are no problems from this.  I wonder if you ran for a long period of time would it drift out of sync?
It seems like Ravenna did finish this code, but left it out of the free driver.  Here is how it looks on a commercial Ravenna device.

<img width="357" alt="Screen Shot 2022-01-19 at 20 34 22" src="https://user-images.githubusercontent.com/3991046/150274228-7b188c7f-d3cb-4957-be78-75f39185a85b.png">

**Comment by bondagit** [comment]
> I wonder if you ran for a long period of time would it drift out of sync

How did you come to this conclusion ? 
No, I don't think so. Sync and Follow Up are sent periodically and clock sync is updated as far as I can see.
Did you perform any measure on this regard ?

**Comment by bondagit** [comment]
Let me try to elaborate a bit.
The PTP slave implementation in the driver doesn't need to be a full implementation as the most important feature for this use case is to make sure that the slave clock speed is the same as the master clock. 
The slave will receive sync (and follow up) messages and it will stay in "unlocked" status until it believes its timestamp clock is changing at the same rate as the master's..When this happens  the clock status is updated to "locked". 
The lack of the request/response delay handling could cause inaccuracies in the determination of the exact master timestamp but will not.lead to a clock drift.

**Comment by llamafilm** [comment]
Thanks for the explanation.  I think you're right.  I haven't done any measurements, only small tests and it all seems fine so far.  I'm still reading through the spec and trying to learn how PTP works.  I'm just surprised that the protocol can function perfectly well with only 2 out of 4 messages.  It always assumes symmetrical propagation time so the meanPathDelay = `[(t2 - t1) + (t4 - t3)] / 2`.  So it's easy to simplify this to just `t2 - t1`, I guess that's what you're doing.
