### ISSUE TITLE
Stuttering and samplerate mismatch Dante

### ISSUE THREAD

**Issue by gubbsjuk** [bondagit/aes67-linux-daemon#65]
Hi!

I am pretty much certain this is user-error...

Im trying to set up a Nanopi-r4s (dual nic) as a Spotify Connect using Librespot. Currently only one Spotify Connect session (stream), but hopefully 2-3 sessions when I get it working.
Done this successfully using a raspberry pi 3 before (albeit with som buffer underruns), but cant for the life of me get it to work with the NanoPi-r4s...

I have tried using the dmix, plughw and hw device in Librespot, I can listen to the sources in Aes67 Monitor, but the source stutter alot. The source is reported in Aes67 Monitor as 44.1kHz sources.  The Initial sample rate in the Daemon is set to 48kHz.
In Dante Controller I cannot subscribe due to Sample Rate mismatch.

**The System:**
Medium sized corporate network with an AHM64 matrix, CDM32 Mixrack, 10 Genelec Dante speakers and 3 LAB amps all on dante, working fine. There are two mutlicast flows on the dante side of things, but i believe that shouldn't be a problem as they default to an IP range outside 239.1.2.1 (wich is where the nano-pi is set to output a stereo channel). Cant remember from the top of my head where Dante defaults to though.

One nic of the R4S is in the dante network and the other nic in the corporate network. Im seeing the streams broadcast over the corporate network aswell. Is there any way to prevent that? I have specified the nic thats in the dante network in the daemon.conf file.

Im sorry for the rambling, hopefully you can make some sense of this, and perhaps point me in the right direction.

Thanks.

**Comment by bondagit** [comment]
Dante supports L24/48Khz configuration only. So the first thing to do is to make sure you create an L24 Source.
The daemon adapts the sample rate announced for a Source according to the playback sample rate: if the playback sample rate changes the announced sample rate gets updated accordingly. 
If you want to playback at 44.1Khz while keeping the Source at 48Khz you can use the dmix plug to handle the conversion. To achieve this add the following configuration to the "/etc/asound.conf" file:
```
pcm.source_1 {
type dmix
ipc_key 0x11111
slave {
pcm "hw:CARD=RAVENNA"
buffer_size 512
channels 4
rate 48000
format S24_3LE
}
bindings { 0 0 1 1 }
}
```
and specify _plug:source_1_ as playback device.
You can try to run a test playback by using aplay or speaker-test.
For example:
`speaker-test -D plug:source_1 -r 48000 -c 2 -t sine `

**Comment by gubbsjuk** [comment]
Hi Andrea!

Thanks for the speedy reply!
I will give this a test in the next few days and get back to you!

Am I correct in assuming this asound.conf is for a 4 channel setup (2 stereo sources) and binds channel 3 and 4 to source_1 ?
For a second stereo stream it whould then be:
```
pcm.source_1 {
    type dmix
    ipc_key 0x11111
    slave {
        pcm "hw:CARD=RAVENNA"
        buffer_size 1024
        channels 4
        rate 48000
        format S24_3LE
     }
    bindings { 1 1 0 0 }
}

pcm.source_2 {
    type dmix
    ipc_key 0x11111
    slave {
        pcm "hw:CARD=RAVENNA"
        buffer_size 1024
        channels 4
        rate 48000
        format S24_3LE
     }
    bindings { 0 0 1 1 }
}
```

Thanks!

**Comment by bondagit** [comment]
The _bindings_ entry associates a channel of the DMIX plugin you are defining with the channel of the PCM device.
So if you want to bind source_1 channels 1 and 2 with the RAVENNA channels 3 and 4 you have to write:
`bindings { 0 2 1 3 }`
channels numbering starts from 0.

**Comment by gubbsjuk** [comment]
Hi Andrea!

With this I'm able to see the stream in Aes67 monitor as 48kHz and listen to it fine.
Im also able to subscribe to it in dante controller, but no audio is passing through using speaker test.

RTP Subscription status is: No audio data.

**Comment by gubbsjuk** [comment]
Gotcha, thank you.

I will looking further into this, probably on the dante/network side of things then.

You can surely close this issue, and I will post an update for future refrence once I figure it out!.

Thanks for all assistance.
