### ISSUE TITLE
I have a problem with CMake

### ISSUE THREAD

**Issue by ManuelGaio** [bondagit/aes67-linux-daemon#66]
Hello Andrea, 

I am having some issues in getting the deamon up and running on a Beaglebone Black (rev.c1) Linux Kernel V4.19.94.  
I flashed Ubuntu 18.04 LTS in the eMMC, installed all the prerequisites following your instructions but when I launch build.sh to compile the application I get the following error: 

****************
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:47 (message):
Could not find compiler set in environment variable CXX:

/usr/bin/clang++.

Call Stack (most recent call first):
CMakeLists.txt:3 (project)

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
****************

I am not too deep into compiling and building systems, can you please advise what I should do to fix this error? Am I doing something wrong? 

FYI the following packages were installed to meet the prerequisites: 
- GCC compiler (v. 7.5.0)
- Boost libraries (v. 1.65.1.0ubuntu1)
- Avahi service (v. 0.8)
- CMake (v. 3.10.2)

I hope you can help me figuring this out. I understand it might be something related to some environment variables but I cannot find how to make it work correctly. Thank you very much.

**Comment by bondagit** [comment]
By default the build.sh tries to compile using clang.
If you want to compile with gcc just comment or remove the following two lines in build.sh:
```
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
```

**Comment by bondagit** [comment]
your compiler version doesn't seem to support the codebase properly. 
Are you able to install and try with clang ?

**Comment by ManuelGaio** [comment]
Thank you for your reply,
using Clang it seems to work, but i'm getting stuck close to the end of the process, at 90%, see below:

[ 75%] Building CXX object CMakeFiles/aes67-daemon.dir/utils.cpp.o
[ 80%] Linking CXX executable aes67-daemon
[ 90%] Built target aes67-daemon

it doesn't move forward, not even after 30 minutes. Any idea?
Thank you again,
Manuel

**Comment by bondagit** [comment]
it looks like you have to update your toolchain in oder to proceed.
