### ISSUE TITLE
Cannot compile driver

### ISSUE THREAD

**Issue by hifi25nl** [bondagit/aes67-linux-daemon#67]
A different error here on Archlinux (kernel 5.16.x):

[audiolinux@archlinux driver]$ make
make -C /lib/modules/5.16.9-AMD/build/ M=/media/linux/Downloads/Temp/ravenna-alsa-lkm/driver modules
make[1]: Entering directory '/usr/lib/modules/5.16.9-AMD/build'
  CC [M]  /media/linux/Downloads/Temp/ravenna-alsa-lkm/driver/c_wrapper_lib.o
  CC [M]  /media/linux/Downloads/Temp/ravenna-alsa-lkm/driver/audio_driver.o
/media/linux/Downloads/Temp/ravenna-alsa-lkm/driver/audio_driver.c: In function ‘mr_alsa_audio_pcm_capture_copy_internal’:
/media/linux/Downloads/Temp/ravenna-alsa-lkm/driver/audio_driver.c:1210:9: error: implicit declaration of function ‘__put_user_x’; did you mean ‘__put_user_8’? [-Werror=implicit-function-declaration]
 1210 |         __put_user_x(1, val, (unsigned long __user *)src, ret_pu);
      |         ^~~~~~~~~~~~
      |         __put_user_8
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:287: /media/linux/Downloads/Temp/ravenna-alsa-lkm/driver/audio_driver.o] Error 1
make[1]: *** [Makefile:1846: /media/linux/Downloads/Temp/ravenna-alsa-lkm/driver] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.16.9-AMD/build'
make: *** [Makefile:14: modules] Error 2

**Comment by bondagit** [comment]
Please use the [aes67-daemon](https://github.com/bondagit/ravenna-alsa-lkm/tree/aes67-daemon) branch of the https://github.com/bondagit/ravenna-alsa-lkm repository. I only maintain that.

**Comment by hifi25nl** [comment]
OK, compiled fine
