### ISSUE TITLE
libboost version

### ISSUE THREAD

**Issue by hifi25nl** [bondagit/aes67-linux-daemon#68]
I have re-compiled the last git version of the daemon with boost-libs 1.78. Still I have:

_/opt/aes67-linux-daemon/aes67-daemon -c /opt/aes67-linux-daemon/aes67-linux-daemon.conf_
/opt/aes67-linux-daemon/aes67-daemon: error while loading shared libraries: libboost_log.so.1.76.0: cannot open shared object file: No such file or directory

**Comment by bondagit** [comment]
please make sure you installed all the boost dev libraries.
On Ubuntu:
`sudo apt-get install -y libboost-all-dev`

**Comment by hifi25nl** [comment]
OK, after a reboot and re-compiling now is fine.
