### ISSUE TITLE
Driver suspend mode can not be disabled

### ISSUE THREAD

**Issue by jnk19** [bondagit/aes67-linux-daemon#69]
HI,

I am just testing the aes67 driver which is working perfect. I have not find though how to keep the stream channel active after the playback is stopped. I have search for a solution on the docs and nowhere seems to be say something about this. Is it implemented on the driver?

I am saying this because some devices want the stream to be active even no audio is present otherwise it drop the connection and not reconnect again until you add it again. Also I have noticed that if playing some tracks and have gap between them the sound card is going to suspend mode and restart when audio is available. I am using alsa only without jack.

Any help would be grateful.

Edit.

Seems the auto-mute function is missing from the driver via amixer.

```
Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback -99 - 0
  Mono: Playback 0 [100%] [0.00dB] [on]
```

Regards.

**Comment by jnk19** [comment]
@bondagit Have you seen this by your side also? I mean this is by default  or am I doing something wrong on installation?

**Comment by bondagit** [comment]
Yes. The driver was originally designed to work like this: the audio stream is delivered if the PTP slave is synchronized and a playback is active on the RAVENNA device. Nothing is delivered otherwise.

**Comment by jnk19** [comment]
So it is impossible to keep the RAVENNA device active even if no playback. I think this is not the correct way for VAD. I am seeking ways to disable this power function via ALSA, I have find for other devices(HDA AC97 and usb audio) but not for ALSA it self. Maybe you have a clue how to produce silence if no playback is active? (meaning a mechanism to keep it alive)

Regards.

**Comment by bondagit** [comment]
> Maybe you have a clue how to produce silence if no playback is active?

You can use the the ALSA dmix plugin for that.
Put the follwoing in /etc/asound.conf: 
```
pcm.source_1 {
type dmix
ipc_key 0x11111
slave {
pcm "hw:CARD=RAVENNA"
buffer_size 512
channels 4
rate 48000
format S24_3LE
}
bindings { 0 0 1 1 }
}
```
Start your silence playback with:
`aplay -D  plug:source_1 -r 48000 -c 2  -f S16_LE  -t raw -vv  < /dev/zero`
Start your file playback on the same device with (for example)
` aplay  -D plug:source_1 -r 48000 -c 2 ./file.wav -vv`
The two playbacks will be mixed by dmix and delivered to the RAVENNA source.
As long as you keep the silence playback active the source stream will be active.

**Comment by bondagit** [comment]
> This somehow should be implemented on the driver

Yes, this could be a valid option but it requires changes to driver.

>  I am seeing on PTP tab that the delta is locked to 0. On an other thread I have read that this is disabled for some reason. Can this be enabled again?

PTP delta measurement is currently not implemented.

>  On this driver the PTP is based on ptp4l or have a built in code?

built in code implementing a PTP slave only. 
I made a change some time ago to support a local PTP master: the built in PTP slave is able to lock on a PTP master (ptp4l is ok) running on the same host.

>  I am seeing that the RAVENNA driver updated and have a fix for 44100 drifting. Can this implemented on your driver?

The driver doesn't implement any sample rate conversion. The sample rate used is the one selected by the running player on the RAVENNA device and the daemon updates the SDP file for the announced sources automatically. If you want to use a fixed sample rate use the dmix plugin and the sample rate conversion will be performed by the ALSA plugin.

**Comment by jnk19** [comment]
Ok got it. Thank you for your response.

Regards.

**Comment by jnk19** [comment]
@bondagit I have one more question and some help needed.

I am trying to control the playback volume via alsamixer but is not possible. I have added the user the @audio group but still nothing. Am I missing something?

Regards.

**Comment by bondagit** [comment]
The RAVENNA alsa driver is a virtual sound card and the volume control is not implemented

**Comment by jnk19** [comment]
OK thank you very much.

Regards.
