### ISSUE TITLE
User defined Node ID?

### ISSUE THREAD

**Issue by Lanthade** [bondagit/aes67-linux-daemon#73]
If I'm reading the documentation right it's not possible to have a user definable (at or after runtime) node ID.  Is that correct?  If so is there any way to change that in the future or is it something that could be set at compile time?  I'd like to be able to use a more friendly and purpose descriptive node ID.

Thanks!

**Comment by bondagit** [comment]
At the moment the node id is automatically generated by the daemon in the attempt to avoid name clashes in case of multiple daemon running on the LAN. 
You can change it to whatever you want by changing the code at:
https://github.com/bondagit/aes67-linux-daemon/blob/480be2577b13957c08101e58c3ee26a4e6582d1a/daemon/utils.cpp#L79

In the future it is possible to add a new daemon configuration option to set it statically.

**Comment by bondagit** [comment]
The fix will be merged to master when daemon v1.5 is complete.

**Comment by bondagit** [comment]
The issue has been solved with v1.5
