### ISSUE TITLE
In the Build.sh, the webui else clause is never reached

### ISSUE THREAD

**Issue by isamubr** [bondagit/aes67-linux-daemon#75]
Hello in the script `build.sh` , it always delete the tar file and download so the else clause that npm install and build is never reached 
The part of the script affected by this from the file. 
```
if  [ -f webui.tar.gz ]; then
  rm -f webui.tar.gz
fi
echo "Downloading current webui release ..."
wget https://github.com/bondagit/aes67-linux-daemon/releases/latest/download/webui.tar.gz
if [ -f webui.tar.gz ]; then
  tar -xzvf webui.tar.gz
else
  echo "Building and installing webui ..."
  # npm install react-modal react-toastify react-router-dom
  npm install
  npm run build
fi
```

**Comment by bondagit** [comment]
yes, the idea is to use the pre-built WebUI when this is available to save time or create it locally otherwise.
I understand the code in else is never reached but still I would like to keep it in case someone wants to create the WebUI locally he knows how to do it.
