### ISSUE TITLE
Deamon compilation stops at utils.cpp.o

### ISSUE THREAD

**Issue by hifi25nl** [bondagit/aes67-linux-daemon#8]
Compilation stops at
error: too few arguments to function ‘std::string httplib::detail::decode_url(const string&, bool)’
-----
[ 80%] Building CXX object CMakeFiles/aes67-daemon.dir/utils.cpp.o
/home/audiolinux/Downloads/NEW/AUR/aes67-linux-daemon/src/aes67-linux-daemon/daemon/utils.cpp: In function ‘std::tuple<bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > parse_url(const string&)’:
/home/audiolinux/Downloads/NEW/AUR/aes67-linux-daemon/src/aes67-linux-daemon/daemon/utils.cpp:42:53: error: too few arguments to function ‘std::string httplib::detail::decode_url(const string&, bool)’
   42 |   std::string url = httplib::detail::decode_url(_url);
      |                                                     ^
In file included from /home/audiolinux/Downloads/NEW/AUR/aes67-linux-daemon/src/aes67-linux-daemon/daemon/utils.hpp:26,
                 from /home/audiolinux/Downloads/NEW/AUR/aes67-linux-daemon/src/aes67-linux-daemon/daemon/utils.cpp:21:
/usr/include/httplib.h:2261:20: note: declared here
 2261 | inline std::string decode_url(const std::string &s,
      |                    ^~~~~~~~~~
make[2]: *** [CMakeFiles/aes67-daemon.dir/build.make:291: CMakeFiles/aes67-daemon.dir/utils.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:116: CMakeFiles/aes67-daemon.dir/all] Error 2
make: *** [Makefile:115: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by bondagit** [comment]
I think you are using a different version the of the [cpp-httplib](https://github.com/yhirose/cpp-httplib) library. 
The daemon is currently using the following revision: https://github.com/yhirose/cpp-httplib/commit/301a419c02
See the [build.sh](build.sh) script.

**Comment by hifi25nl** [comment]
Ok, thanks, that fixed it.
