### ISSUE TITLE
General question about synchronization of RAVENNA soundcard with other soundcards to provide good audio quality

### ISSUE THREAD

**Issue by anthonio9** [bondagit/aes67-linux-daemon#90]
I've been researching RAVENNA for linux for half a year now. One constant problem I'm trying to solve for months now is a task of synchronizing RAVENNA soundcard with any other soundcard, that has access to a DAC. RAVENNA is obviously responsible for audio reception, the other one for audio playback (it could be an RCA output or headphone jack output). Without synchronization the quality of audio drops very quickly, click or noise appear and are really disturbing. So far I were not able to get a constant stream of clear audio out of RAVENNA set on a raspberry pi 4 platform, no matter what I tried. And I tried a lot: PREEMPT_RT kernel, JUCE, pipewire, alsaloop (with -S parameter set to 3 or 5 for auto). In all cases, immediately or after a short time the audio quality drops. 

Do you have any advice on how to handle this issue? Is hardware ptp support necessary for a good audio synchronization, maybe phy2sys would help in that case to synchronize system clock with the ptp master clock? (I assume that software soundcards such as RAVENNA base their clock on either on of these). Is the Raspberry platform not ideal for this usecase as it does nto support hardware PTP time-stamping?

My usual setup is a RPI4 with RAVENNA daemon and PTP master clock (patch from one of the issues). This is an audio reception and playback device. The role of audio stream sending device is usually played by my linux laptop with another instance of RAVENNA daemon.

Did you by any change find a set of setting that just works? 
Without the synchronization the whole concept of audio over IP looses it's all advantages.

**Comment by neoscopio** [comment]
Hi, I got this working, but I'm using a pi as a sink, a regular desktop as a source, and a **different** desktop as a master clock.
Have you tried with a "regular" non-patched ptp4l running on its own? 
anyway, atm by best latency in the pi is `End to end latency: 7.998 msecs` what is yours?

**Comment by anthonio9** [comment]
I'm not able to test the setup that you described right now, I remember that such configuration provided much better quality, but I really want to have this ptp4l instance running locally as well. What did you use for end to end latency? Is is the tool available in this repo?

**Comment by anthonio9** [comment]
In the end I got a better audio quality out of a setup where PTP Master runs on a Laptop with hardware ptp timestamping support, rpi is just a follower. Occasional clicks (underruns/overruns) occur every 30s to a few minutes, so it's not perfectly clear. Do you have any idea why that could be and how to make it work better?

**Comment by neoscopio** [comment]
Yes, I measured latency using the latency script. I did get some clicks, I am using an alsaloop to stream to the driver, and I got rid of the clicks by tweaking loop values and priority. 
btw: You don't need to set up a slave clock on the pi, the driver will do that for you, I made that mistake myself.

**Comment by anthonio9** [comment]
What do you mean by priority, how can it be tweaked? I'm aware about the driver handling the slave ptp clock, I wasn't clear enough - my bad. Indeed there is only driver ptp clock running on the rpi.

**Comment by neoscopio** [comment]
I'm currently running this:

`sudo nice -n -10 alsaloop -b -c 2 -r 48000 -f S16_LE -C plughw:RAVENNA -P hw:0,0`

but you could also use 
`sudo chrt -f 99` comand

**Comment by anthonio9** [comment]
I think the `nice` prioritization helped a little, but xruns still happen. Unfortunately I'm not able to measure the latency with the tool provided by this repo, somehow every time the latency program returns `End to end latency: no samples collected`. Do you now how to cope with that? 
```sh
$ sudo ./latency -C hw:RAVENNA -P hw:RAVENNA -r 48000 -s 15 -m 128 -M 128 -p
Scheduler set to Round Robin with priority 99...
Playback device is hw:RAVENNA
Capture device is hw:RAVENNA
Parameters are 48000Hz, S16_LE, 2 channels, non-blocking mode
Poll mode: yes
Loop limit is 720000 frames, minimum latency = 128, maximum latency = 128
Hardware PCM card 1 'Merging RAVENNA' device 0 subdevice 0
Its setup is:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 16
  buffer_size  : 128
  period_size  : 64
  period_time  : 1333
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 64
  period_event : 0
  start_threshold  : 2147483647
  stop_threshold   : 128
  silence_threshold: 0
  silence_size : 0
  boundary     : 4611686018427387904
  appl_ptr     : 0
  hw_ptr       : 0
Hardware PCM card 1 'Merging RAVENNA' device 0 subdevice 0
Its setup is:
  stream       : CAPTURE
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 16
  buffer_size  : 128
  period_size  : 64
  period_time  : 1333
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 64
  period_event : 0
  start_threshold  : 2147483647
  stop_threshold   : 128
  silence_threshold: 0
  silence_size : 0
  boundary     : 4611686018427387904
  appl_ptr     : 0
  hw_ptr       : 0
Trying latency 128 frames, 2666.667us, 2.666667ms (375.0000Hz)
Success
Playback:
*** frames = 720128 ***
  state       : RUNNING
  trigger_time: 2908.581687
  tstamp      : 0.000000
  delay       : 128
  avail       : 0
  avail_max   : 64
Capture:
*** frames = 720000 ***
  state       : RUNNING
  trigger_time: 2908.581688
  tstamp      : 0.000000
  delay       : 0
  avail       : 0
  avail_max   : 64
Maximum read: 64 frames
Maximum read latency: 1333.333us, 1.333333ms (750.0000Hz)
Playback time = 2908.581687, Record time = 2908.581688, diff = -1
End to end latency: no samples collected
```

Interestingly, the results are the same no matter if on the other end the alsaloop software is running or not. Pulse audio was not running during that test. If neither poll or block mode is used than `xrun` state is detected and the measurement fails, like below:

```sh
$ sudo ./latency -C hw:RAVENNA -P hw:RAVENNA -r 48000 -s 5 -m 128 -M 128
Scheduler set to Round Robin with priority 99...
Playback device is hw:RAVENNA
Capture device is hw:RAVENNA
Parameters are 48000Hz, S16_LE, 2 channels, non-blocking mode
Poll mode: no
Loop limit is 240000 frames, minimum latency = 128, maximum latency = 128
Hardware PCM card 1 'Merging RAVENNA' device 0 subdevice 0
Its setup is:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 16
  buffer_size  : 128
  period_size  : 64
  period_time  : 1333
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 64
  period_event : 0
  start_threshold  : 2147483647
  stop_threshold   : 128
  silence_threshold: 0
  silence_size : 0
  boundary     : 4611686018427387904
  appl_ptr     : 0
  hw_ptr       : 0
Hardware PCM card 1 'Merging RAVENNA' device 0 subdevice 0
Its setup is:
  stream       : CAPTURE
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 16
  buffer_size  : 128
  period_size  : 64
  period_time  : 1333
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 64
  period_event : 0
  start_threshold  : 2147483647
  stop_threshold   : 128
  silence_threshold: 0
  silence_size : 0
  boundary     : 4611686018427387904
  appl_ptr     : 0
  hw_ptr       : 0
Trying latency 128 frames, 2666.667us, 2.666667ms (375.0000Hz)
Failure
Playback:
*** frames = 45888 ***
  state       : XRUN
  trigger_time: 3061.259412
  tstamp      : 0.000000
  delay       : 0
  avail       : 64
  avail_max   : 64
Capture:
*** frames = 45760 ***
  state       : XRUN
  trigger_time: 3061.259412
  tstamp      : 0.000000
  delay       : 0
  avail       : 128
  avail_max   : 128
Maximum read: 64 frames
Maximum read latency: 1333.333us, 1.333333ms (750.0000Hz)
End to end latency: no samples collected
```

Thank you for your help @neoscopio!

**Comment by neoscopio** [comment]
You should be able to run the  ./run_latency_test.sh. Your parameters don't specify number of channels.

Try this:

`sudo ./run_latency_test.sh S24_3LE 48000 2 60` [128, 256, 512, 1024, 2048, 4096, 8192 ...]

Start at `128` and keep doubling it until you dont see xruns.
