### ISSUE TITLE
build fail with newer kernel modules 5.18.0-5.1-liquorix-amd64

### ISSUE THREAD

**Issue by toadzroc** [bondagit/aes67-linux-daemon#92]
$ ./build.sh
Cloning into 'ravenna-alsa-lkm'...
remote: Enumerating objects: 873, done.
remote: Counting objects: 100% (873/873), done.
remote: Compressing objects: 100% (464/464), done.
remote: Total 873 (delta 423), reused 830 (delta 384), pack-reused 0
Receiving objects: 100% (873/873), 5.26 MiB | 965.00 KiB/s, done.
Resolving deltas: 100% (423/423), done.
make -C /lib/modules/5.18.0-5.1-liquorix-amd64/build/ M=/home/alex/Downloads/git/aes67-linux-daemon/3rdparty/ravenna-alsa-lkm/driver modules
make[1]: *** /lib/modules/5.18.0-5.1-liquorix-amd64/build/: No such file or directory.  Stop.
make: *** [Makefile:14: modules] Error 2

**Comment by bondagit** [comment]
Did you install the kernel headers and all the needed dependencies ?
See script ubuntu-packages.sh

**Comment by toadzroc** [comment]
I did, except for one.

Sorry for the noise. AES is now installed and works.
